In [10]:
from collections import Counter
import json
import sys
import os
import re

import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_colwidth', None)
pd.set_option('display.min_rows', 100)

In [11]:
pharmgkb_root = '/home/april/projects/opentargets/pharmgkb'
clinical_annotations = pd.read_csv(os.path.join(pharmgkb_root, 'clinical', 'clinical_annotations.tsv'), sep='\t')

In [12]:
variants = pd.read_csv(os.path.join(pharmgkb_root, 'variants', 'variants.tsv'), sep='\t')

In [13]:
clinical_ann_alleles = pd.read_csv(os.path.join(pharmgkb_root, 'clinical', 'clinical_ann_alleles.tsv'), sep='\t')

In [14]:
ca_with_rs = clinical_annotations[clinical_annotations['Variant/Haplotypes'].str.contains('rs')]

In [21]:
calleles_with_rs = clinical_ann_alleles[
    clinical_ann_alleles['Clinical Annotation ID'].isin(ca_with_rs['Clinical Annotation ID'])
]

### Option 1

* Use `clinical_ann_alleles.tsv` but only the column with alleles, not the free text.
* Use this to get the alleles relevant to the given clinical annotation, then resolve which is ref/alt via... (allele frequencies?  order in the column? something else?)
    * Ensembl allele string - assuming first is always ref (?)
* Get chrom & pos from NCBI/Ensembl or `variants.tsv`
* Won't work for a few rsid records (5013 total > 4416 with rsid > 4350 with exactly 2 alleles)

In [22]:
len(clinical_annotations)

5013

In [23]:
len(ca_with_rs)

4416

In [24]:
results_2_alleles = set()
results_more_alleles = set()
results_not_snps = set()
# Check whether only 2 alleles involved - if so we can determine which is ref (probably)
for x in ca_with_rs['Clinical Annotation ID']:
    alleles = set()
    not_snp = False
    for ga in calleles_with_rs[calleles_with_rs['Clinical Annotation ID'] == x]['Genotype/Allele']:
        # x chrom
        if len(ga) == 1:
            alleles.add(ga)
            continue
        # snp
        if len(ga) == 2:
            alleles.add(ga[0])
            alleles.add(ga[1])
            continue
        # "simple" allele
        m = re.match('([ACGT]+|del)/([ACGT]+|del)', ga, re.IGNORECASE)
        if not m:
            not_snp = True
            break
        alleles.add(m.group(1))
        alleles.add(m.group(2))
    if not_snp:
        results_not_snps.add(x)
    elif len(alleles) <= 2:
        results_2_alleles.add(x)
    else:
        results_more_alleles.add(x)

In [25]:
len(results_2_alleles)

4350

In [26]:
len(results_more_alleles)

51

In [27]:
len(results_not_snps)

15

In [74]:
calleles_with_rs[calleles_with_rs['Clinical Annotation ID'].isin(results_2_alleles)].head()

,Clinical Annotation ID,Genotype/Allele,Annotation Text,Allele Function
0,981755803,AA,"Patients with the rs75527207 AA genotype (two copies of the CFTR G551D variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
1,981755803,AG,"Patients with the rs75527207 AG genotype (one copy of the CFTR G551D variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
2,981755803,GG,"Patients with the rs75527207 GG genotype (do not have a copy of the CFTR G551D variant) and cystic fibrosis have an unknown response to ivacaftor treatment, as response may depend on the presence of other CFTR variants. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
3,1449311190,CC,"Patients with the CC genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need a decreased dose of mercaptopurine, or methotrexate, as compared to children with the TT genotype. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.",NaN
4,1449311190,CT,"Patients with the CT genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need a decreased dose of mercaptopurine, or methotrexate, as compared to children with the TT genotype. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.",NaN

In [28]:
calleles_with_rs[calleles_with_rs['Clinical Annotation ID'].isin(results_not_snps)]

,Clinical Annotation ID,Genotype/Allele,Annotation Text,Allele Function
2303,1183617783,(CCCACCCGA)9/(CCCACCCGA)9,Patients with the (CCCACCCGA)9/(CCCACCCGA)9 genotype and depression who are treated with antidepressants 1) may have a reduced risk of adverse drug reactions after switching treatment for the second time 2) may be less likely to have a lack of a response to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. Other genetic and clinical factors may also influence a patient's response to treatment.,NaN
2304,1183617783,(CCCACCCGA)10/(CCCACCCGA)9,Patients with the (CCCACCCGA)10/(CCCACCCGA)9 genotype and depression who are treated with antidepressants 1) may have a reduced risk of adverse drug reactions after switching treatment for the second time 2) may be less likely to have a lack of a response to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. Other genetic and clinical factors may also influence a patient's response to treatment.,NaN
2305,1183617783,(CCCACCCGA)10/(CCCACCCGA)10,Patients with the (CCCACCCGA)10/(CCCACCCGA)10 genotype and depression who are treated with antidepressants 1) may have a reduced risk of adverse drug reactions after switching treatment for the second time 2) may be less likely to have a lack of a response to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. Other genetic and clinical factors may also influence a patient's response to treatment.,NaN
2306,1183617783,(CCCACCCGA)12/(CCCACCCGA)9,Patients with the (CCCACCCGA)12/(CCCACCCGA)9 genotype and depression who are treated with antidepressants 1) may have a reduced risk of adverse drug reactions after switching treatment for the second time 2) may be less likely to have a lack of a response to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. Other genetic and clinical factors may also influence a patient's response to treatment.,NaN
2307,1183617783,(CCCACCCGA)12/(CCCACCCGA)10,Patients with the (CCCACCCGA)12/(CCCACCCGA)10 genotype and depression who are treated with antidepressants 1) may have a reduced risk of adverse drug reactions after switching treatment for the second time 2) may be less likely to have a lack of a response to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. Other genetic and clinical factors may also influence a patient's response to treatment.,NaN
2308,1183617783,(CCCACCCGA)12/(CCCACCCGA)12,Patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype and depression who are treated with antidepressants 1) may have an increased risk of adverse drug reactions after switching treatment for the second time 2) may be more likely to have a lack of a response to treatment as compared to other genotypes. Other genetic and clinical factors may also influence a patient's response to treatment.,NaN
2732,1183615328,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2,Patients with the rs45445694 2R/2R genotype ((CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2) and colorectal cancer may have a decreased risk of asthenia when treated with irinotecan and raltitrexed as compared to patients with the 2R/3R or 3R/3R genotype. Other genetic and clinical factors may also influence risk of asthenia.,NaN
2733,1183615328,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3,Patients with the rs45445694 2R/3R genotype ((CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3) and colorectal cancer may have an increased risk of asthenia when treated with irinotecan and raltitrexed as compared to patients with the 2R/2R genotype. Other genetic and clinical factors may also influence risk of asthenia.,NaN
2734,1183615328,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3,Patients with the rs45445694 3R/3R genotype ((CCGCGCCACTTGGCCTGCCTCCGTCCCG)3/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3) and colorectal cancer may have an increased risk of asthenia when treated with irinotecan and raltitrexed as compared to patients with the 2R/2R genotype. Other genetic and clinical factors may also influence risk of asthenia.,NaN
3134,1183617765,(CCCACCCGA)9/(CCCACCCGA)9,"Patients with the (CCCACCCGA)9/(CCCACCCGA)9 genotype and depression who are treated with fluoxetine may be less likely to respond to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
3135,1183617765,(CCCACCCGA)10/(CCCACCCGA)9,"Patients with the (CCCACCCGA)10/(CCCACCCGA)9 genotype and depression who are treated with fluoxetine may be less likely to respond to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
3136,1183617765,(CCCACCCGA)10/(CCCACCCGA)10,"Patients with the (CCCACCCGA)10/(CCCACCCGA)10 genotype and depression who are treated with fluoxetine may be less likely to respond to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
3137,1183617765,(CCCACCCGA)12/(CCCACCCGA)9,"Patients with the (CCCACCCGA)12/(CCCACCCGA)9 genotype and depression who are treated with fluoxetine may be less likely to respond to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
3138,1183617765,(CCCACCCGA)12/(CCCACCCGA)10,"Patients with the (CCCACCCGA)12/(CCCACCCGA)10 genotype and depression who are treated with fluoxetine may be less likely respond to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
3139,1183617765,(CCCACCCGA)12/(CCCACCCGA)12,"Patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype and depression who are treated with fluoxetine may have a better response to treatment as compared to other genotypes. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
5249,655385323,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2,Patients with the rs45445694 2R/2R genotype ((CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2) may have increased response to methotrexate in people with Rheumatoid Arthritis as compared to patients with the 2R/3R or 3R/3R genotypes. Other genetic and clinical factors may also influence response to methotrexate.,NaN
5250,655385323,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3,Patients with the rs45445694 2R/3R genotype ((CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3) may have decreased response to methotrexate in people with Rheumatoid Arthritis as compared to patients with the 2R/2R genotype. Other genetic and clinical factors may also influence response to methotrexate.,NaN
5251,655385323,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3,Patients with the rs45445694 3R/3R genotype ((CCGCGCCACTTGGCCTGCCTCCGTCCCG)3/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3) may have decreased response to methotrexate in people with Rheumatoid Arthritis as compared to patients with the 2R/2R genotype. Other genetic and clinical factors may also influence response to methotrexate.,NaN
5385,981188336,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2,"Patients with the rs45445694 2R/2R genotype ((CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2) may have increased progression-free survival when treated with methotrexate chemotherapy regimens compared to patients with the 3R/3R genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence response to methotrexate.",NaN
5386,981188336,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3,"Patients with the rs45445694 2R/3R genotype ((CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3) may have increased progression-free survival when treated with methotrexate chemotherapy regimens compared to patients with the 3R/3R genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence response to methotrexate.",NaN
5387,981188336,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3,"Patients with the rs45445694 3R/3R genotype ((CCGCGCCACTTGGCCTGCCTCCGTCCCG)3/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3) may have decreased progression-free survival when treated with methotrexate chemotherapy regimens compared to patients with the 2R/2R genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence response to methotrexate.",NaN
5546,981475986,(CA)16/(CA)16,Patients with the (CA)16/(CA)16 genotype and non-small cell lung cancer may have increased clinical response when treated with gefitinib as compared to patients with the (CA)17/(CA)17. Other genetic and clinical factors may also influence gefitinib response.,NaN
5547,981475986,(CA)16/(CA)17,Patients with the (CA)16/(CA)17 genotype and non-small cell lung cancer may have increased clinical response when treated with gefitinib as compared to patients with the (CA)17/(CA)17. Other genetic and clinical factors may also influence gefitinib response.,NaN
5548,981475986,(CA)17/(CA)17,Patients with the (CA)17/(CA)17 genotype and non-small cell lung cancer may have decreased clinical response when treated with gefitinib as compared to patients with the (CA)16/(CA)16 or (CA)16/(CA)17. Other genetic and clinical factors may also influence gefitinib response.,NaN
5920,1451436180,CCCCCCC,Patients with the 961delT+C(n) allele (represented here by the rs1556422499 CCCCCCC allele) may have an increased risk of experiencing aminoglycoside-induced hearing loss as compared to patients with the T allele. MT-RNR1 is a mitochondrial gene and is inherited as a haploid (i.e. there is only ever one allele present). Other genetic and clinical factors may also influence risk of aminoglycoside-induced hearing loss.,NaN
5921,1451436180,T,"Patients with the rs1556422499 T allele (also known as the 961T allele) may have a decreased, but not absent, risk of experiencing aminoglycoside-induced hearing loss as compared to patients with a delT+C(n) allele (e.g. CCCCCCC). MT-RNR1 is a mitochondrial gene and is inherited as a haploid (i.e. there is only ever one allele present). Other genetic and clinical factors may also influence risk of aminoglycoside-induced hearing loss.",NaN
6029,1451436481,CCCCCCC,"Patients with the 961delT+C(n) allele (represented here by the rs1556422499 CCCCCCC allele) may have an increased risk of experiencing hearing loss when treated with streptomycin as compared to patients with the T allele. However, conflicting evidence has been reported. MT-RNR1 is a mitochondrial gene and is inherited as a haploid (i.e. there is only ever one allele present). Other genetic and clinical factors may also influence risk of hearing loss when treated with streptomycin.",NaN
6030,1451436481,T,"Patients with the rs1556422499 T allele (also known as the 961T allele) may have a decreased, but not absent, risk of experiencing hearing loss when treated with streptomycin as compared to patients with a delT+C(n) allele (e.g. CCCCCCC). However, conflicting evidence has been reported. MT-RNR1 is a mitochondrial gene and is inherited as a haploid (i.e. there is only ever one allele present). Other genetic and clinical factors may also influence risk of hearing loss when treated with streptomycin.",NaN
6034,1451436473,CCCCCCC,Patients with the 961delT+C(n) allele (represented here by the rs1556422499 CCCCCCC allele) may have an increased risk of experiencing hearing loss when treated with dihydrostreptomycin as compared to patients with the T allele. MT-RNR1 is a mitochondrial gene and is inherited as a haploid (i.e. there is only ever one allele present). Other genetic and clinical factors may also influence risk of hearing loss when treated with dihydrostreptomycin.,NaN
6035,1451436473,T,"Patients with the rs1556422499 T allele (also known as the 961T allele) may have a decreased, but not absent, risk of experiencing hearing loss when treated with dihydrostreptomycin as compared to patients with a delT+C(n) allele (e.g. CCCCCCC). MT-RNR1 is a mitochondrial gene and is inherited as a haploid (i.e. there is only ever one allele present). Other genetic and clinical factors may also influence risk of hearing loss when treated with dihydrostreptomycin.",NaN
9074,1444607379,(CCCACCCGA)9,"Patients with the (CCCACCCGA)9 allele and depression who are treated with sertraline may have a less response to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, contradictory findings report no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
9075,1444607379,(CCCACCCGA)10,"Patients with the (CCCACCCGA)10 allele and depression who are treated with sertraline may have a less response to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, contradictory findings report no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
9076,1444607379,CCCACCCGA)12/(CCCACCCGA)12,"Patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype and depression who are treated with sertraline may have a better response to treatment as compared to other genotypes. However, contradictory findings report no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
9331,1183697617,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2,"Patients with the rs45445694 (CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2 or 2R/2R genotype and blood cancers may have an increased risk for drug toxicity when treated with methotrexate as compared to patients with the 2R/3R or 3R/3R genotypes. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence risk for drug toxicity.",NaN
9332,1183697617,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3,"Patients with the rs45445694 (CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3 or 2R/3R genotype and blood cancers may have a decreased risk for drug toxicity when treated with methotrexate as compared to patients with the 2R/2R genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence risk for drug toxicity.",NaN
9333,1183697617,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3,"Patients with the rs45445694 (CCGCGCCACTTGGCCTGCCTCCGTCCCG)3/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3 or 3R/3R genotype and blood cancers may have a decreased risk for drug toxicity when treated with methotrexate as compared to patients with the 2R/2R genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence risk for drug toxicity.",NaN
13022,1447991729,(CCCACCCGA)9/(CCCACCCGA)9,"Patients with the (CCCACCCGA)9/(CCCACCCGA)9 genotype and depression who are treated with paroxetine may be less likely to respond to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
13023,1447991729,(CCCACCCGA)10/(CCCACCCGA)9,"Patients with the (CCCACCCGA)10/(CCCACCCGA)9 genotype and depression who are treated with paroxetine may be less likely to respond to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
13024,1447991729,(CCCACCCGA)10/(CCCACCCGA)10,"Patients with the (CCCACCCGA)10/(CCCACCCGA)10 genotype and depression who are treated with paroxetine may be less likely to respond to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
13025,1447991729,(CCCACCCGA)12/(CCCACCCGA)9,"Patients with the (CCCACCCGA)12/(CCCACCCGA)9 genotype and depression who are treated with paroxetine may be less likely to respond to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
13026,1447991729,(CCCACCCGA)12/(CCCACCCGA)10,"Patients with the (CCCACCCGA)12/(CCCACCCGA)10 genotype and depression who are treated with paroxetine may be less likely respond to treatment as compared to patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
13027,1447991729,(CCCACCCGA)12/(CCCACCCGA)12,"Patients with the (CCCACCCGA)12/(CCCACCCGA)12 genotype and depression who are treated with paroxetine may have a better response to treatment as compared to other genotypes. However, a contradictory finding reports no association of the (CCCACCCGA)12 allele and response. Other genetic and clinical factors may also influence a patient's response to treatment.",NaN
13915,1451114600,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2,"Patients with the rs45445694 (CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2 or 2R/2R genotype may have an increased risk for toxicity when treated with fluorouracil chemotherapy regimens as compared to patients with 3R/3R genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence risk for fluorouracil toxicity.",NaN
13916,1451114600,(CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3,"Patients with the rs45445694 (CCGCGCCACTTGGCCTGCCTCCGTCCCG)2/(CCGCGCCACTTGGCCTGCCTCCGTCCCG)3 or 2R/3R genotype may have an increased risk for toxicity when treated with fluorouracil chemotherapy regimens as compared to patients with the 3R/3R genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence risk for fluorouracil toxicity.",NaN

In [29]:
calleles_with_rs[calleles_with_rs['Clinical Annotation ID'].isin(results_more_alleles)]

,Clinical Annotation ID,Genotype/Allele,Annotation Text,Allele Function
160,1450375701,AA,"Patients with the AA genotype may have a decreased response to allopurinol as compared to patients with the AC, CC or CT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.",NaN
161,1450375701,AC,"Patients with the AC genotype may have an increased response to allopurinol as compared to patients with the AA, AT or TT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.",NaN
162,1450375701,AT,"Patients with the AT genotype may have a decreased response to allopurinol as compared to patients with the AC, CC or CT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.",NaN
163,1450375701,CC,"Patients with the CC genotype may have an increased response to allopurinol as compared to patients with the AA, AT or TT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.",NaN
164,1450375701,CT,"Patients with the CT genotype may have an increased response to allopurinol as compared to patients with the AA, AT or TT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.",NaN
165,1450375701,TT,"Patients with the TT genotype may have a decreased response to allopurinol as compared to patients with the AC, CC or CT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.",NaN
757,1449004745,AA,Patients with Mesothelioma and the AA genotype may have worse overall and progression-free survival when treated with cisplatin and gemcitabine as compared to patients with the CC genotype. Other clinical and genetic factors may also influence response to cisplatin and gemcitabine in patients with mesothelioma.,NaN
758,1449004745,AG,Patients with Mesothelioma and the AC genotype may have worse overall and progression-free survival when treated with cisplatin and gemcitabine as compared to patients with the CC genotype. Other clinical and genetic factors may also influence response to cisplatin and gemcitabine in patients with mesothelioma.,NaN
759,1449004745,CC,Patients with Mesothelioma and the CC genotype may have improved overall and progression-free survival when treated with cisplatin and gemcitabine as compared to patients with the AA and AC genotype. Other clinical and genetic factors may also influence response to cisplatin and gemcitabine in patients with mesothelioma.,NaN
799,1449645498,AA,"Patients with the AA genotype may have an increased rate of sulfation of acetaminophen as compared to patients with the CC, CT, or TT genotypes. Other genetic and clinical factors may also affect acetaminophen sulfation in patients.",NaN
800,1449645498,AC,"Patients with the AC genotype may have an increased rate of sulfation of acetaminophen as compared to patients with the CC, CT, or TT genotypes. Other genetic and clinical factors may also affect acetaminophen sulfation in patients.",NaN
801,1449645498,AT,There is currently no published evidence to suggest how the AT genotype may affect acetaminophen sulfation in patients.,NaN
802,1449645498,CC,"Patients with the CC genotype may have an increased rate of sulfation of acetaminophen as compared to patients with the CT or TT genotypes, but a decreased rate of acetaminophen sulfation as compared to patients with the AA or AC genotypes. Other genetic and clinical factors may also affect acetaminophen sulfation in patients.",NaN
803,1449645498,CT,"Patients with the CT genotype may have a decreased rate of sulfation of acetaminophen as compared to patients with the AA, AC or CC genotypes. Other genetic and clinical factors may also affect acetaminophen sulfation in patients.",NaN
804,1449645498,TT,"Patients with the TT genotype may have a decreased rate of sulfation of acetaminophen as compared to patients with the AA, AC or CC genotypes. Other genetic and clinical factors may also affect acetaminophen sulfation in patients.",NaN
808,1449645513,AA,"Patients with the AA genotype may have an increased rate of sulfation of tapentadol as compared to patients with the CC, CT, or TT genotypes. Other genetic and clinical factors may also affect tapentadol sulfation in patients.",NaN
809,1449645513,AC,"Patients with the AC genotype may have an increased rate of sulfation of tapentadol as compared to patients with the CC, CT, or TT genotypes. Other genetic and clinical factors may also affect tapentadol sulfation in patients.",NaN
810,1449645513,AT,There is currently no published evidence to suggest how the AT genotype may affect tapentadol sulfation in patients.,NaN
811,1449645513,CC,"Patients with the CC genotype may have an increased rate of sulfation of tapentadol as compared to patients with the CT or TT genotypes, but a decreased rate of tapentadol sulfation as compared to patients with the AA or AC genotypes. Other genetic and clinical factors may also affect tapentadol sulfation in patients.",NaN
812,1449645513,CT,"Patients with the CT genotype may have a decreased rate of sulfation of tapentadol as compared to patients with the AA, AC or CC genotypes. Other genetic and clinical factors may also affect tapentadol sulfation in patients.",NaN
813,1449645513,TT,"Patients with the TT genotype may have a decreased rate of sulfation of tapentadol as compared to patients with the AA, AC or CC genotypes. Other genetic and clinical factors may also affect tapentadol sulfation in patients.",NaN
814,1449645522,AA,"Patients with the AA genotype may have an increased rate of sulfation of O-desmethyl-tramadol, a metabolite of tramadol, as compared to patients with the CC, CT, or TT genotypes. Other genetic and clinical factors may also affect O-desmethyl-tramadol sulfation in patients.",NaN
815,1449645522,AC,"Patients with the AC genotype may have an increased rate of sulfation of O-desmethyl-tramadol as compared to patients with the CC, CT, or TT genotypes. Other genetic and clinical factors may also affect O-desmethyl-tramadol sulfation in patients.",NaN
816,1449645522,AT,There is currently no published evidence to suggest how the AT genotype may affect O-desmethyl-tramadol sulfation in patients.,NaN
817,1449645522,CC,"Patients with the CC genotype may have an increased rate of sulfation of O-desmethyl-tramadol as compared to patients with the CT or TT genotypes, but a decreased rate of O-desmethyl-tramadol sulfation as compared to patients with the AA or AC genotypes. Other genetic and clinical factors may also affect O-desmethyl-tramadol sulfation in patients.",NaN
818,1449645522,CT,"Patients with the CT genotype may have a decreased rate of sulfation of O-desmethyl-tramadol as compared to patients with the AA, AC or CC genotypes. Other genetic and clinical factors may also affect O-desmethyl-tramadol sulfation in patients.",NaN
819,1449645522,TT,"Patients with the TT genotype may have a decreased rate of sulfation of O-desmethyl-tramadol as compared to patients with the AA, AC or CC genotypes. Other genetic and clinical factors may also affect O-desmethyl-tramadol sulfation in patients.",NaN
1186,1152661500,AA,Patients with the AA genotype and Hypercholesterolemia who are treated with simvastatin may have a reduced risk of developing myalgia as compared to patients with the CC genotype. Other genetic and clinical factors may also influence a patient's risk of simvastatin-induced adverse drug reactions.,NaN
1187,1152661500,AC,Patients with the AC genotype and Hypercholesterolemia who are treated with simvastatin may have an increased risk of developing myalgia as compared to patients with the AA or TT genotype. Other genetic and clinical factors may also influence a patient's risk of simvastatin-induced adverse drug reactions.,NaN
1188,1152661500,AT,Patients with the AT genotype and Hypercholesterolemia who are treated with simvastatin may have a reduced developing myalgia as compared to patients with the CC genotype. Other genetic and clinical factors may also influence a patient's risk of simvastatin-induced adverse drug reactions.,NaN
...,...,...,...,...
14087,1449167512,AA,Patients with the AA genotype and Attention Deficit Disorder with Hyperactivity may have a decreased response to treatment with methylphenidate as compared to patients who carry the G allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14088,1449167512,AG,Patients with the AG genotype and Attention Deficit Disorder with Hyperactivity may have an increased response to treatment with methylphenidate as compared to patients who do not carry the G allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14089,1449167512,AT,Patients with the AT genotype and Attention Deficit Disorder with Hyperactivity may have a decreased response to treatment with methylphenidate as compared to patients who carry the G allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14090,1449167512,GG,Patients with the GG genotype and Attention Deficit Disorder with Hyperactivity may have an increased response to treatment with methylphenidate as compared to patients who do not carry the G allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14091,1449167512,GT,Patients with the GT genotype and Attention Deficit Disorder with Hyperactivity may have an increased response to treatment with methylphenidate as compared to patients who do not carry the G allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14092,1449167512,TT,Patients with the TT genotype and Attention Deficit Disorder with Hyperactivity may have a decreased response to treatment with methylphenidate as compared to patients who carry the G allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14093,1449167529,AA,Patients with the AA genotype and Attention Deficit Disorder with Hyperactivity may have a decreased response to treatment with methylphenidate as compared to patients who carry the C allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14094,1449167529,AC,Patients with the AC genotype and Attention Deficit Disorder with Hyperactivity may have an increased response to treatment with methylphenidate as compared to patients who do not carry the C allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14095,1449167529,AT,Patients with the AT genotype and Attention Deficit Disorder with Hyperactivity may have a decreased response to treatment with methylphenidate as compared to patients who carry the C allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14096,1449167529,CC,Patients with the CC genotype and Attention Deficit Disorder with Hyperactivity may have an increased response to treatment with methylphenidate as compared to patients who do not carry the C allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14097,1449167529,CT,Patients with the CT genotype and Attention Deficit Disorder with Hyperactivity may have an increased response to treatment with methylphenidate as compared to patients who do not carry the C allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14098,1449167529,TT,Patients with the TT genotype and Attention Deficit Disorder with Hyperactivity may have a decreased response to treatment with methylphenidate as compared to patients who carry the C allele. Other genetic and clinical factors may also affect a patient's response to methylphenidate,NaN
14351,1450811035,CC,"Patients with the CC genotype may experience decreased inhibition of KCNH2 by disopyramide as compared to patients with the GG genotype. However, this decrease in inhibition is not considered to be clinically significant. Other genetic and clinical factors may also affect inhibition of KCNH2 by disopyramide.",NaN
14352,1450811035,CG,"Patients with the CG genotype may experience decreased inhibition of KCNH2 by disopyramide as compared to patients with the GG genotype. However, this decrease in inhibition is not considered to be clinically significant. Other genetic and clinical factors may also affect inhibition of KCNH2 by disopyramide.",NaN
14353,1450811035,CT,"Patients with the CT genotype may experience decreased inhibition of KCNH2 by disopyramide as compared to patients with the GG genotype. However, this decrease in inhibition is not considered to be clinically significant. Other genetic and clinical factors may also affect inhibition of KCNH2 by disopyramide.",NaN
14354,1450811035,GG,Patients with the GG genotype may experience increased inhibition of KCNH2 by disopyramide as compared to patients carrying at least one C or T allele. Other genetic and clinical factors may also affect inhibition of KCNH2 by disopyramide.,NaN
14355,1450811035,GT,"Patients with the GT genotype may experience decreased inhibition of KCNH2 by disopyramide as compared to patients with the GG genotype. However, this decrease in inhibition is not considered to be clinically significant. Other genetic and clinical factors may also affect inhibition of KCNH2 by disopyramide.",NaN
14356,1450811035,TT,"Patients with the TT genotype may experience decreased inhibition of KCNH2 by disopyramide as compared to patients with the GG genotype. However, this decrease in inhibition is not considered to be clinically significant. Other genetic and clinical factors may also affect inhibition of KCNH2 by disopyramide.",NaN
14357,1450811044,CC,Patients with the CC genotype may experience decreased inhibition of KCNH2 by quinidine as compared to patients the GG genotype. Other genetic and clinical factors may also affect inhibition of KCNH2 by quinidine.,NaN
14358,1450811044,CG,Patients with the CG genotype may experience decreased inhibition of KCNH2 by quinidine as compared to patients the GG genotype. Other genetic and clinical factors may also affect inhibition of KCNH2 by quinidine.,NaN
14359,1450811044,CT,Patients with the CT genotype may experience decreased inhibition of KCNH2 by quinidine as compared to patients the GG genotype. Other genetic and clinical factors may also affect inhibition of KCNH2 by quinidine.,NaN
14360,1450811044,GG,Patients with the GG genotype may experience increased inhibition of KCNH2 by quinidine as compared to patients carrying at least one C or T allele. Other genetic and clinical factors may also affect inhibition of KCNH2 by quinidine.,NaN
14361,1450811044,GT,Patients with the GT genotype may experience decreased inhibition of KCNH2 by quinidine as compared to patients the GG genotype. Other genetic and clinical factors may also affect inhibition of KCNH2 by quinidine.,NaN
14362,1450811044,TT,Patients with the TT genotype may experience decreased inhibition of KCNH2 by quinidine as compared to patients the GG genotype. Other genetic and clinical factors may also affect inhibition of KCNH2 by quinidine.,NaN
14677,1450934668,CC,"Patients with the CC genotype have an unknown response to migalastat, as response may depend on the presence of other GLA variants. Other genetic and clinical factors may also affect a patient's response to migalastat.",NaN
14678,1450934668,CG,Patients with the CG genotype may respond to migalastat for the treatment of Fabry disease. Other genetic and clinical factors may also affect a patient's response to migalastat.,NaN
14679,1450934668,CT,"Patients with the CT genotype have an unknown response to migalastat, as response may depend on the presence of other GLA variants. Other genetic and clinical factors may also affect a patient's response to migalastat.",NaN
14680,1450934668,GG,Patients with the GG genotype may respond to migalastat for the treatment of Fabry disease. Other genetic and clinical factors may also affect a patient's response to migalastat.,NaN
14681,1450934668,GT,Patients with the GT genotype may respond to migalastat for the treatment of Fabry disease. Other genetic and clinical factors may also affect a patient's response to migalastat.,NaN
14682,1450934668,TT,"Patients with the TT genotype have an unknown response to migalastat, as response may depend on the presence of other GLA variants. Other genetic and clinical factors may also affect a patient's response to migalastat.",NaN

In [75]:
clinical_annotations[clinical_annotations['Clinical Annotation ID'] == 1450375701]

,Clinical Annotation ID,Variant/Haplotypes,Gene,Level of Evidence,Level Override,Level Modifiers,Score,Phenotype Category,PMID Count,Evidence Count,Drug(s),Phenotype(s),Latest History Date (YYYY-MM-DD),URL,Specialty Population
47,1450375701,rs4659982,GREM2,3,NaN,NaN,0.0,Efficacy,1,1,allopurinol,NaN,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1450375701,NaN

Examples of how to get from clinical annotation to `chr_pos_ref_alt`

In [31]:
import requests

In [62]:
def get_coordinates_for_rs(rsid):
    # can do this in bulk too probably - batches of 200
    if not rsid.startswith('rs'):
        rsid = f'rs{rsid}'
    ensembl_url = f'https://rest.ensembl.org/variation/human/{rsid}?content-type=application/json'
    resp = requests.get(ensembl_url)
    data = resp.json()
    if 'mappings' in data:
        for m in data['mappings']:
            if m['assembly_name'] == 'GRCh38':
                break
        chrom = m['seq_region_name']
        pos = m['start']
        alleles = m['allele_string'].split('/')
        ref = alleles[0]
        alts = alleles[1:]
        return chrom, pos, ref, alts
    return None, None, None, None

In [132]:
def get_coordinates_for_clinical_annotation(caid):
    rs = ca_with_rs[ca_with_rs['Clinical Annotation ID'] == caid]['Variant/Haplotypes'].iloc[0]
    chrom, pos, ref, alts = get_coordinates_for_rs(rs)
    if not chrom or not pos or not ref or not alts:
        return None
    if len(alts) == 1:
        return f'{chrom}_{pos}_{ref}_{alts[0]}'
    # If multiple alts, check what is referred to in the clinical alleles table
    alleles = set()
    for ga in calleles_with_rs[calleles_with_rs['Clinical Annotation ID'] == caid]['Genotype/Allele']:
        # x chrom
        if len(ga) == 1:
            alleles.add(ga)
            continue
        # snp
        if len(ga) == 2:
            alleles.add(ga[0])
            alleles.add(ga[1])
            continue
        # "simple" allele
        m = re.match('([ACGT]+|del)/([ACGT]+|del)', ga, re.IGNORECASE)
        if not m:
            break
        alleles.add(convert_allele(m.group(1)))
        alleles.add(convert_allele(m.group(2)))
    for a in alleles:
        if a in alts:
            return f'{chrom}_{pos}_{ref}_{a}'
    return None

In [97]:
def convert_allele(allele):
    if allele.lower() == 'del':
        return '-'
    return allele

In [135]:
for caid in ca_with_rs['Clinical Annotation ID'].sample(n=1000):
    coords = get_coordinates_for_clinical_annotation(caid)
    print(f'https://www.pharmgkb.org/clinicalAnnotation/{caid} => {coords}')

https://www.pharmgkb.org/clinicalAnnotation/1444704267 => 5_7649747_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451125666 => 14_94587675_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449157547 => 6_31481199_C_A
https://www.pharmgkb.org/clinicalAnnotation/1449168433 => 4_129255324_G_T
https://www.pharmgkb.org/clinicalAnnotation/1043880328 => CHR_HSCHR22_1_CTG7_24034135_G_A
https://www.pharmgkb.org/clinicalAnnotation/637880078 => 2_169154475_T_C
https://www.pharmgkb.org/clinicalAnnotation/982030948 => 11_27712873_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448125544 => 14_61740839_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449168579 => 12_5916985_A_G
https://www.pharmgkb.org/clinicalAnnotation/655384922 => 6_15627871_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447952936 => 20_8591578_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449191770 => 7_117642528_G_T
https://www.pharmgkb.org/clinicalAnnotation/1449156815 => 11_2165105_A_G
https://www.pharmgkb.org/clinicalAnnotation/655384954 => X_114731326_C_G
https://www.pharmgkb.org/clinicalAnnotation/1448103889 => 9_101585868_G_A
https://www.pharmgkb.org/clinicalAnnotation/1185000225 => 7_99672916_T_C
https://www.pharmgkb.org/clinicalAnnotation/1296666989 => 2_233759291_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444702771 => 6_24503362_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447987124 => 1_237826822_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444666789 => 11_72139084_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444704048 => 5_37818037_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447814153 => 4_55125972_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183681861 => 1_156899922_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450820863 => 11_113425564_C_T
https://www.pharmgkb.org/clinicalAnnotation/982031026 => 7_87527735_G_A
https://www.pharmgkb.org/clinicalAnnotation/1445401274 => 4_69095621_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447813873 => 6_151916333_T_C
https://www.pharmgkb.org/clinicalAnnotation/1444703803 => None
https://www.pharmgkb.org/clinicalAnnotation/1448604316 => 19_6679500_C_T
https://www.pharmgkb.org/clinicalAnnotation/1184764189 => 6_31039078_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451138166 => 2_170815568_C_G
https://www.pharmgkb.org/clinicalAnnotation/655384934 => 12_96044775_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444680131 => 5_79517086_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043858675 => 19_55025227_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183614721 => 2_67746755_T_G
https://www.pharmgkb.org/clinicalAnnotation/1447944806 => 22_40831082_C_G
https://www.pharmgkb.org/clinicalAnnotation/1450811978 => 6_154090869_G_C
https://www.pharmgkb.org/clinicalAnnotation/1447959752 => 11_126157578_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449004522 => 16_53045702_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448101238 => 6_31574531_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448257270 => 15_55830149_T_G
https://www.pharmgkb.org/clinicalAnnotation/1451409133 => 16_56962376_G_A
https://www.pharmgkb.org/clinicalAnnotation/613977037 => 6_31810495_G_A
https://www.pharmgkb.org/clinicalAnnotation/981201399 => 10_99804058_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449167420 => 4_158680524_C_T
https://www.pharmgkb.org/clinicalAnnotation/655386176 => 8_18400860_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450811035 => 7_150951629_G_T
https://www.pharmgkb.org/clinicalAnnotation/1444700916 => 20_23046984_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449716392 => 7_87531302_A_T
https://www.pharmgkb.org/clinicalAnnotation/1451149992 => 2_27508073_T_C
https://www.pharmgkb.org/clinicalAnnotation/1444607295 => 6_88140381_T_C
https://www.pharmgkb.org/clinicalAnnotation/1450928499 => 10_133537858_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448615614 => 12_2681966_A_G
https://www.pharmgkb.org/clinicalAnnotation/827864159 => 4_3004316_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183622263 => 1_156909788_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449271349 => 6_154039561_C_T
https://www.pharmgkb.org/clinicalAnnotation/1446899372 => 4_88131171_G_T
https://www.pharmgkb.org/clinicalAnnotation/1446899722 => 4_21385141_T_A
https://www.pharmgkb.org/clinicalAnnotation/1183702964 => 11_27658369_C_T
https://www.pharmgkb.org/clinicalAnnotation/637879631 => 17_30237328_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447989671 => 1_97450066_GG_G
https://www.pharmgkb.org/clinicalAnnotation/1448100194 => 21_28055779_G_T
https://www.pharmgkb.org/clinicalAnnotation/1451263986 => 1_201060815_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183619322 => 7_87536434_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450812210 => 6_154040884_C_T
https://www.pharmgkb.org/clinicalAnnotation/1184514209 => 2_159042977_G_T
https://www.pharmgkb.org/clinicalAnnotation/1451131846 => 19_38900291_C_G
https://www.pharmgkb.org/clinicalAnnotation/655386649 => None
https://www.pharmgkb.org/clinicalAnnotation/1448097822 => 15_81937658_A_C
https://www.pharmgkb.org/clinicalAnnotation/1449565416 => 10_94972166_G_T
https://www.pharmgkb.org/clinicalAnnotation/1043859119 => 6_35621293_C_A
https://www.pharmgkb.org/clinicalAnnotation/1449566697 => 9_113262744_A_C
https://www.pharmgkb.org/clinicalAnnotation/1444607366 => 12_77042368_C_T
https://www.pharmgkb.org/clinicalAnnotation/655385579 => 7_150992991_C_T
https://www.pharmgkb.org/clinicalAnnotation/982044867 => 11_69648142_G_A
https://www.pharmgkb.org/clinicalAnnotation/655385818 => 6_31575254_G_A
https://www.pharmgkb.org/clinicalAnnotation/655387835 => 1_11796321_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448602108 => 4_68822269_A_C
https://www.pharmgkb.org/clinicalAnnotation/1444700509 => 4_88131171_G_T
https://www.pharmgkb.org/clinicalAnnotation/1444703502 => 17_63476833_T_A
https://www.pharmgkb.org/clinicalAnnotation/982032442 => 9_84986054_T_G
https://www.pharmgkb.org/clinicalAnnotation/1447963049 => 1_65610269_G_C
https://www.pharmgkb.org/clinicalAnnotation/1448112196 => 2_233718962_T_G
https://www.pharmgkb.org/clinicalAnnotation/1451223592 => 19_41006936_G_T
https://www.pharmgkb.org/clinicalAnnotation/981201770 => 12_20858546_T_G
https://www.pharmgkb.org/clinicalAnnotation/1447945967 => 7_86774159_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451635027 => 11_69648142_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451398000 => 10_114045297_G_C
https://www.pharmgkb.org/clinicalAnnotation/699639328 => 10_95051288_G_C
https://www.pharmgkb.org/clinicalAnnotation/1448604251 => 7_87531302_A_T
https://www.pharmgkb.org/clinicalAnnotation/1450812229 => 1_28835097_T_C
https://www.pharmgkb.org/clinicalAnnotation/1444607302 => 6_88163211_T_G
https://www.pharmgkb.org/clinicalAnnotation/1448428117 => 10_117250954_C_T
https://www.pharmgkb.org/clinicalAnnotation/655386131 => 10_72009749_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183533945 => 10_99844450_C_T
https://www.pharmgkb.org/clinicalAnnotation/981239773 => 19_39252525_T_G
https://www.pharmgkb.org/clinicalAnnotation/1184348872 => 6_39082846_T_A
https://www.pharmgkb.org/clinicalAnnotation/1451398293 => 18_60183864_T_C
https://www.pharmgkb.org/clinicalAnnotation/655386447 => 11_10303778_C_A
https://www.pharmgkb.org/clinicalAnnotation/1451599340 => 2_165311993_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450376188 => 11_17388025_T_C
https://www.pharmgkb.org/clinicalAnnotation/1450815166 => 11_80347435_G_C
https://www.pharmgkb.org/clinicalAnnotation/981755820 => 7_117559591_TCTT_T
https://www.pharmgkb.org/clinicalAnnotation/1449144292 => 5_88619764_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449645474 => 16_30200780_G_T
https://www.pharmgkb.org/clinicalAnnotation/1184472764 => 10_103138228_T_C
https://www.pharmgkb.org/clinicalAnnotation/1445401001 => 2_38071060_G_C
https://www.pharmgkb.org/clinicalAnnotation/1451637140 => 6_154069472_C_T
https://www.pharmgkb.org/clinicalAnnotation/655384602 => 1_163063901_C_T
https://www.pharmgkb.org/clinicalAnnotation/1445400672 => 9_117700861_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043880659 => 6_152061247_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449140279 => 5_83177826_A_G

https://www.pharmgkb.org/clinicalAnnotation/1451648420 => 16_84814217_C_T
https://www.pharmgkb.org/clinicalAnnotation/1446899736 => 4_21391993_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449168565 => 12_5916418_G_C
https://www.pharmgkb.org/clinicalAnnotation/1183615373 => 16_50712015_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449713738 => 1_12192898_T_G
https://www.pharmgkb.org/clinicalAnnotation/1184233504 => 22_19962712_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451354700 => 19_40998172_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447990902 => 6_43768652_A_C
https://www.pharmgkb.org/clinicalAnnotation/1450935819 => 10_94942203_A_C
https://www.pharmgkb.org/clinicalAnnotation/1447980968 => 6_160134722_G_A
https://www.pharmgkb.org/clinicalAnnotation/655385286 => 4_88112375_T_C
https://www.pharmgkb.org/clinicalAnnotation/981203689 => 10_99782821_C_T
https://www.pharmgkb.org/clinicalAnnotation/1043880802 => 12_21178615_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451131781 => 14_35405317_T_A
https://www.pharmgkb.org/clinicalAnnotation/982031723 => 2_233620997_C_T
https://www.pharmgkb.org/clinicalAnnotation/981238550 => 1_225831932_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451666355 => 19_40849833_C_G
https://www.pharmgkb.org/clinicalAnnotation/1450375716 => 2_14177682_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451114072 => 2_21028042_G_A
https://www.pharmgkb.org/clinicalAnnotation/1445401847 => 19_45409478_C_A
https://www.pharmgkb.org/clinicalAnnotation/1448265565 => 6_24992899_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183615383 => 13_95030989_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444667585 => 9_132906834_T_C
https://www.pharmgkb.org/clinicalAnnotation/1446906391 => 14_64233327_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451636580 => 12_21229685_T_C
https://www.pharmgkb.org/clinicalAnnotation/1183630271 => 9_113224129_T_G
https://www.pharmgkb.org/clinicalAnnotation/1449747617 => 19_38448673_C_T
https://www.pharmgkb.org/clinicalAnnotation/655384817 => 6_12296022_G_T
https://www.pharmgkb.org/clinicalAnnotation/1444686921 => 2_112840530_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449311190 => 12_21178615_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449168314 => 1_168683252_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448102666 => 14_104766758_C_A
https://www.pharmgkb.org/clinicalAnnotation/1449713666 => 12_56093417_T_C
https://www.pharmgkb.org/clinicalAnnotation/637879869 => 8_63026205_G_A
https://www.pharmgkb.org/clinicalAnnotation/1184988860 => 12_13800184_T_A
https://www.pharmgkb.org/clinicalAnnotation/1448100165 => 10_66576537_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451634914 => 1_236885200_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447814482 => 1_159304153_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183631465 => 22_46202410_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444704784 => 4_3004316_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183491809 => 6_31575254_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449575690 => 1_97595124_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451135380 => 7_87531302_A_C
https://www.pharmgkb.org/clinicalAnnotation/1451476060 => 11_69648142_G_A
https://www.pharmgkb.org/clinicalAnnotation/1446896644 => 11_27658369_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444673197 => 6_43770057_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183492244 => 7_44541392_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451150004 => 2_57815106_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451244900 => 22_19963748_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444672826 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450824225 => 19_44908684_T_C
https://www.pharmgkb.org/clinicalAnnotation/655385033 => 17_39723335_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183705797 => 19_38494564_C_T
https://www.pharmgkb.org/clinicalAnnotation/982031767 => 15_74749576_C_A
https://www.pharmgkb.org/clinicalAnnotation/1451125538 => 6_31269077_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448276370 => 13_108267192_T_C
https://www.pharmgkb.org/clinicalAnnotation/1183679813 => 2_205609288_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447964136 => 10_133526341_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449645386 => 16_29461414_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444667432 => 1_111314586_G_A
https://www.pharmgkb.org/clinicalAnnotation/1446899688 => 20_51419700_A_T
https://www.pharmgkb.org/clinicalAnnotation/1451640212 => 2_186089405_A_G
https://www.pharmgkb.org/clinicalAnnotation/1184749280 => 17_81510981_G_A
https://www.pharmgkb.org/clinicalAnnotation/1446908686 => 20_41163423_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183623069 => 17_50691125_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450826993 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449270486 => 4_39413373_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043859380 => 16_89920200_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448098299 => 1_161237587_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448522754 => 2_79673969_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450375728 => 4_88040419_C_T
https://www.pharmgkb.org/clinicalAnnotation/1446902905 => 9_11018077_C_A
https://www.pharmgkb.org/clinicalAnnotation/1444666601 => 9_97697296_T_C
https://www.pharmgkb.org/clinicalAnnotation/1450813825 => 11_113910259_T_C
https://www.pharmgkb.org/clinicalAnnotation/1184987397 => 6_52580583_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451238365 => 6_154061407_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451476309 => 10_99836239_T_A
https://www.pharmgkb.org/clinicalAnnotation/1449718271 => 10_94781859_G_A
https://www.pharmgkb.org/clinicalAnnotation/655385178 => 16_15992976_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450823791 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183704316 => 6_43768652_A_C
https://www.pharmgkb.org/clinicalAnnotation/1447983050 => 10_118836909_T_C
https://www.pharmgkb.org/clinicalAnnotation/1154221922 => 4_88131171_G_T
https://www.pharmgkb.org/clinicalAnnotation/1448102543 => 12_57768302_G_T
https://www.pharmgkb.org/clinicalAnnotation/1444704032 => 9_129739602_A_C
https://www.pharmgkb.org/clinicalAnnotation/1451282140 => 15_51210647_A_C
https://www.pharmgkb.org/clinicalAnnotation/1448423682 => 1_67240275_G_A
https://www.pharmgkb.org/clinicalAnnotation/981202090 => 16_55823658_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444608284 => 10_65919290_A_G
https://www.pharmgkb.org/clinicalAnnotation/1446901311 => 5_132657117_C_T
https://www.pharmgkb.org/clinicalAnnotation/1156497684 => 15_74752237_A_T
https://www.pharmgkb.org/clinicalAnnotation/982037368 => 17_47283364_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449168357 => 3_21757155_T_A
https://www.pharmgkb.org/clinicalAnnotation/1447959745 => 9_125370928_T_C
https://www.pharmgkb.org/clinicalAnnotation/1185000534 => 3_119799570_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449191401 => 7_117530955_C_A
https://www.pharmgkb.org/clinicalAnnotation/1444704141 => 5_40679465_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447961178 => 7_55019087_A_C
https://www.pharmgkb.org/clinicalAnnotation/1447961074 => 6_44386904_C_T
https://www.pharmgkb.org/clinicalAnnotation/1446906363 => 11_113412737_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444703339 => 14_52313933_C_G
https://www.pharmgkb.org/clinicalAnnotation/981238041 => 7_87531302_A_C
https://www.pharmgkb.org/clinicalAnnotation/1448526040 => 6_154124080_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447749024 => 16_69711242_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448097711 => 1_47335173_A_C
https://www.pharmgkb.org/clinicalAnnotation/637879967 => 7_95294544_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448258925 => 10_99782821_C_T
https://www.pharmgkb.org/clinicalAnnotation/655384975 => 1_163070705_G_T
https://www.pharmgkb.org/clinicalAnnotation/1449190397 => 6_154090110_G_T
https://www.pharmgkb.org/clinicalAnnotation/1446906328 => 3_119805244_G_T
https://www.pharmgkb.org/clinicalAnnotation/1450823852 => 11_113400106_G_A
https://www.pharmgkb.org/clinicalAnnotation/982037378 => 5_53051539_C_T

https://www.pharmgkb.org/clinicalAnnotation/1183614676 => 18_60183864_T_C
https://www.pharmgkb.org/clinicalAnnotation/981238397 => 11_67585218_A_G
https://www.pharmgkb.org/clinicalAnnotation/619523414 => 7_87531245_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449146840 => 6_44233216_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450812204 => 11_68685517_G_A
https://www.pharmgkb.org/clinicalAnnotation/1043873008 => 5_63955024_T_G
https://www.pharmgkb.org/clinicalAnnotation/1449167120 => 16_84975857_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451131761 => 1_206484465_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448100229 => 19_11131982_T_C
https://www.pharmgkb.org/clinicalAnnotation/1445401008 => 1_201060815_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448532002 => 12_20930928_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451440020 => MT_1189_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449168412 => 4_129244309_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444668468 => 19_44912383_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183682148 => 4_69096360_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447521683 => 19_44908822_C_T
https://www.pharmgkb.org/clinicalAnnotation/637879785 => 1_225831952_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444607789 => 11_113932306_A_C
https://www.pharmgkb.org/clinicalAnnotation/1444704067 => 15_74735539_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450826913 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447673669 => 19_38499975_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447960411 => 2_127418286_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183702417 => 19_39244466_T_C
https://www.pharmgkb.org/clinicalAnnotation/1444667334 => 10_87960494_T_C
https://www.pharmgkb.org/clinicalAnnotation/655384842 => 10_95067273_C_T
https://www.pharmgkb.org/clinicalAnnotation/1184233486 => 22_19962429_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043858840 => 10_94937118_C_T
https://www.pharmgkb.org/clinicalAnnotation/1446908580 => 3_183990651_T_C
https://www.pharmgkb.org/clinicalAnnotation/1450932374 => 1_11794419_T_G
https://www.pharmgkb.org/clinicalAnnotation/1444703768 => 12_6845711_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449188725 => 6_154061407_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043859494 => X_114731326_C_G
https://www.pharmgkb.org/clinicalAnnotation/1448615153 => 15_51242350_C_A
https://www.pharmgkb.org/clinicalAnnotation/1449168065 => 2_50438029_T_A
https://www.pharmgkb.org/clinicalAnnotation/1450823123 => 6_154093438_C_T
https://www.pharmgkb.org/clinicalAnnotation/981202294 => 19_41006936_G_T
https://www.pharmgkb.org/clinicalAnnotation/655386616 => 19_45351661_T_G
https://www.pharmgkb.org/clinicalAnnotation/1444608189 => 18_683607_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450811346 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1445401420 => 2_233774704_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451336100 => 7_87504050_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451274984 => 1_97450058_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183564845 => 3_148742201_A_C
https://www.pharmgkb.org/clinicalAnnotation/1447963042 => 11_113400106_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451131735 => 8_42300384_T_C
https://www.pharmgkb.org/clinicalAnnotation/1450826969 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450371701 => 1_161544752_A_C
https://www.pharmgkb.org/clinicalAnnotation/1183700536 => 9_22096056_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449564951 => 11_17388025_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449168531 => 12_5915594_T_C
https://www.pharmgkb.org/clinicalAnnotation/1043880229 => None
https://www.pharmgkb.org/clinicalAnnotation/1183704404 => 1_160546518_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183615535 => 7_87550285_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449189242 => 1_200273504_G_A
https://www.pharmgkb.org/clinicalAnnotation/1184748889 => 5_80644324_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447983071 => 10_118856240_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449575662 => 1_97515923_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449140229 => 7_87550285_A_G
https://www.pharmgkb.org/clinicalAnnotation/655386985 => 22_24440056_T_C
https://www.pharmgkb.org/clinicalAnnotation/982029652 => 1_46405089_C_A
https://www.pharmgkb.org/clinicalAnnotation/1447953192 => 10_111076745_G_C
https://www.pharmgkb.org/clinicalAnnotation/1450813875 => 19_40986013_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183629475 => 12_13564574_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451493693 => 3_148742201_A_C
https://www.pharmgkb.org/clinicalAnnotation/1183614807 => 12_6844093_A_C
https://www.pharmgkb.org/clinicalAnnotation/1448573300 => 16_30999862_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449309937 => 19_38499645_GGAGGAG_GGAG
https://www.pharmgkb.org/clinicalAnnotation/1444668808 => 17_63488530_ATACAGTCACTTTT_ATACAGTCACTTTTTTTTTTTTTTTGAGACGGAGTCTCGCTCTGTCGCCCATACAGTCACTTTT
https://www.pharmgkb.org/clinicalAnnotation/1449169484 => 4_69096360_T_C
https://www.pharmgkb.org/clinicalAnnotation/1446897159 => 2_112832813_G_A
https://www.pharmgkb.org/clinicalAnnotation/981420042 => 7_55191822_T_G
https://www.pharmgkb.org/clinicalAnnotation/1450934761 => None
https://www.pharmgkb.org/clinicalAnnotation/1448101044 => 5_154651307_T_C
https://www.pharmgkb.org/clinicalAnnotation/981345293 => 12_21178615_T_C
https://www.pharmgkb.org/clinicalAnnotation/1444694385 => 2_240603286_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448109558 => 2_138023362_T_C
https://www.pharmgkb.org/clinicalAnnotation/1184134274 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/655384878 => 10_82059369_T_G
https://www.pharmgkb.org/clinicalAnnotation/1450376319 => 1_196899970_T_G
https://www.pharmgkb.org/clinicalAnnotation/1449168058 => 1_178597251_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447963798 => 4_3037423_T_C
https://www.pharmgkb.org/clinicalAnnotation/1445401413 => 2_233774704_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450934711 => X_101397982_C_T
https://www.pharmgkb.org/clinicalAnnotation/827848732 => 11_69648142_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448100326 => 4_69096657_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447961144 => 14_65977626_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447987211 => 6_20679478_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451674418 => 19_40848688_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450812235 => 11_113904553_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449192313 => 7_117590355_C_A
https://www.pharmgkb.org/clinicalAnnotation/1183680555 => 17_45130754_A_T
https://www.pharmgkb.org/clinicalAnnotation/1449157957 => 20_54170358_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444703430 => 10_68399112_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447953199 => 10_111076745_G_C
https://www.pharmgkb.org/clinicalAnnotation/1448100444 => 11_113412966_C_A
https://www.pharmgkb.org/clinicalAnnotation/1451649186 => 10_5218719_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183679122 => 15_45328787_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183491098 => 2_43839108_G_C
https://www.pharmgkb.org/clinicalAnnotation/1451434930 => MT_1555_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444705206 => 7_30660356_G_C
https://www.pharmgkb.org/clinicalAnnotation/1183704277 => 4_99412110_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449171120 => 19_41016810_C_T
https://www.pharmgkb.org/clinicalAnnotation/1445401439 => 10_94988738_A_T
https://www.pharmgkb.org/clinicalAnnotation/1184986174 => 1_97579893_G_C
https://www.pharmgkb.org/clinicalAnnotation/1448101073 => 7_128394575_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183698818 => 2_233760498_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449271015 => 19_18129545_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447959508 => 6_159692840_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448100567 => 10_99844450_C_T
https://www.pharmgkb.org/clinicalAnnotation/655385333 => 16_79405477_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451403720 => 4_103643921_G_A

https://www.pharmgkb.org/clinicalAnnotation/827848751 => 6_151842246_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451434925 => MT_1555_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183622527 => 15_74746626_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183563324 => 12_6845711_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447673027 => 16_31093557_G_A
https://www.pharmgkb.org/clinicalAnnotation/769143802 => 17_63488670_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451114960 => None
https://www.pharmgkb.org/clinicalAnnotation/1444686836 => 1_206773289_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449747881 => 7_99648291_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043858975 => 19_3595796_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451120986 => 12_99455122_G_T
https://www.pharmgkb.org/clinicalAnnotation/1183704330 => 1_230710048_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447943693 => 3_114171968_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449005066 => 7_99784473_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449192431 => 7_117642465_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449190104 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450932250 => 10_94780653_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447989732 => 1_97593343_C_A
https://www.pharmgkb.org/clinicalAnnotation/1444703951 => 9_133279294_T_G
https://www.pharmgkb.org/clinicalAnnotation/655387027 => 1_20588679_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448432217 => 2_136115514_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449715919 => 7_87531302_A_T
https://www.pharmgkb.org/clinicalAnnotation/1444703976 => 15_63341039_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448099162 => 20_44429378_T_C
https://www.pharmgkb.org/clinicalAnnotation/1444703985 => 11_113422198_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449270943 => 11_128937143_C_T
https://www.pharmgkb.org/clinicalAnnotation/1445401156 => 1_163143470_G_T
https://www.pharmgkb.org/clinicalAnnotation/1447989796 => 1_97382318_T_C
https://www.pharmgkb.org/clinicalAnnotation/1143918642 => 3_148741522_G_A
https://www.pharmgkb.org/clinicalAnnotation/981419550 => 1_237826822_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447943640 => 10_49630828_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451737520 => 8_90925381_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449718265 => 10_94761900_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449144352 => 2_200121622_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183679828 => 6_117494965_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451263980 => 1_201060815_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451105200 => 12_21178615_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451648366 => 5_43969952_A_G
https://www.pharmgkb.org/clinicalAnnotation/655387895 => 5_80654345_-_TGGCGCGTCCCGCCCAGGT
https://www.pharmgkb.org/clinicalAnnotation/1444706201 => 12_21164857_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448603303 => 1_46399999_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450963020 => 19_45364001_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183632140 => 9_84294635_G_A
https://www.pharmgkb.org/clinicalAnnotation/655386070 => 21_36073015_G_A
https://www.pharmgkb.org/clinicalAnnotation/637879590 => 10_95067273_C_T
https://www.pharmgkb.org/clinicalAnnotation/981237930 => 19_45420395_A_G
https://www.pharmgkb.org/clinicalAnnotation/1446906439 => 7_87531302_A_C
https://www.pharmgkb.org/clinicalAnnotation/1444700605 => 17_7000625_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449188737 => 6_154072003_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183960790 => 7_117664770_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447964123 => 8_18390208_T_A
https://www.pharmgkb.org/clinicalAnnotation/1451504280 => 3_165830599_-_C
https://www.pharmgkb.org/clinicalAnnotation/981201817 => 19_40845362_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447962710 => 15_58431476_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444704775 => 9_101615721_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183614835 => 15_74720644_T_A
https://www.pharmgkb.org/clinicalAnnotation/1183614591 => 2_166036278_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450822281 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451674160 => 19_40844634_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451737600 => 10_133368948_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449645486 => 16_30200780_G_T
https://www.pharmgkb.org/clinicalAnnotation/1450823887 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451637183 => 22_41993944_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449713231 => 1_209942767_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447987080 => 7_87522787_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451868540 => 10_119340641_T_G
https://www.pharmgkb.org/clinicalAnnotation/981238288 => 7_87531302_A_C
https://www.pharmgkb.org/clinicalAnnotation/827923042 => 19_41006936_G_T
https://www.pharmgkb.org/clinicalAnnotation/1451637147 => 6_154069472_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448102633 => 3_179148620_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183700857 => 6_43771240_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451599354 => 2_165311993_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451638961 => 7_87550285_A_G
https://www.pharmgkb.org/clinicalAnnotation/1184987041 => 7_87600877_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043858606 => 11_27658369_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451141160 => 19_8949865_C_T
https://www.pharmgkb.org/clinicalAnnotation/1043858877 => 4_156090771_G_T
https://www.pharmgkb.org/clinicalAnnotation/1448266396 => 7_99768693_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449005195 => 7_65908864_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447982712 => 22_42126750_G_A
https://www.pharmgkb.org/clinicalAnnotation/982032512 => 9_85017403_C_T
https://www.pharmgkb.org/clinicalAnnotation/1445400992 => 1_204547449_A_G
https://www.pharmgkb.org/clinicalAnnotation/1445402111 => 22_19963748_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451640205 => 1_56417819_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448635585 => 19_41006936_G_T
https://www.pharmgkb.org/clinicalAnnotation/1043880664 => 6_154040884_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450936248 => 16_28607005_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450814563 => 4_46388848_C_G
https://www.pharmgkb.org/clinicalAnnotation/1451131852 => 19_50377484_T_C
https://www.pharmgkb.org/clinicalAnnotation/655388510 => 11_113475530_G_GG
https://www.pharmgkb.org/clinicalAnnotation/981202714 => 4_2904980_G_T
https://www.pharmgkb.org/clinicalAnnotation/655386436 => 1_11794419_T_G
https://www.pharmgkb.org/clinicalAnnotation/1444607979 => 11_4138699_C_A
https://www.pharmgkb.org/clinicalAnnotation/981188353 => 2_233693545_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450959460 => 12_102866632_C_T
https://www.pharmgkb.org/clinicalAnnotation/1043880170 => 16_56962376_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451344820 => 1_101409030_T_G
https://www.pharmgkb.org/clinicalAnnotation/655386151 => 16_16157742_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444704921 => 10_99844450_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449140085 => 7_87531302_A_C
https://www.pharmgkb.org/clinicalAnnotation/1447960191 => 5_148826910_G_C
https://www.pharmgkb.org/clinicalAnnotation/1183680531 => 8_117172544_C_T
https://www.pharmgkb.org/clinicalAnnotation/655386099 => 10_72013004_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448109598 => 7_87444459_G_T
https://www.pharmgkb.org/clinicalAnnotation/1451126040 => 20_54174979_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447987227 => 1_74572544_A_C
https://www.pharmgkb.org/clinicalAnnotation/1451476540 => 11_67585218_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451131820 => 1_206496132_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448624459 => 15_55335330_A_G
https://www.pharmgkb.org/clinicalAnnotation/655385973 => 10_99836239_T_A
https://www.pharmgkb.org/clinicalAnnotation/1444666629 => 19_45364001_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448276321 => 16_53826140_G_A

https://www.pharmgkb.org/clinicalAnnotation/1451263060 => 6_93420339_T_C
https://www.pharmgkb.org/clinicalAnnotation/655385409 => 10_114044277_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447963057 => MT_10398_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450373100 => 10_90859404_T_G
https://www.pharmgkb.org/clinicalAnnotation/1447982754 => 22_42127596_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450935844 => 10_94775395_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183700253 => 11_4092165_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449168621 => 12_5917412_T_A
https://www.pharmgkb.org/clinicalAnnotation/1448103928 => 3_119781188_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451226220 => 22_19957654_A_G
https://www.pharmgkb.org/clinicalAnnotation/1445401377 => 5_148826877_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447681831 => 15_51215311_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449144298 => 6_25177280_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451151340 => 17_7676154_G_C
https://www.pharmgkb.org/clinicalAnnotation/1444703154 => 18_63318540_C_T
https://www.pharmgkb.org/clinicalAnnotation/981204890 => 11_113400106_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444668298 => 12_53429100_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450810351 => 6_154083178_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444705174 => 6_15650901_G_A
https://www.pharmgkb.org/clinicalAnnotation/981203518 => 22_24441333_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448600720 => 1_205930467_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448262901 => 19_15879621_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451407321 => 13_46895805_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451550960 => 4_153704257_T_C
https://www.pharmgkb.org/clinicalAnnotation/1450826899 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447983940 => 15_74749576_C_A
https://www.pharmgkb.org/clinicalAnnotation/1449168405 => 4_96767816_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451566760 => 11_113400106_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451721004 => 6_93730886_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043880293 => 19_41016810_C_T
https://www.pharmgkb.org/clinicalAnnotation/1446899729 => 4_21389571_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448099828 => 10_44372809_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448636848 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/981204851 => 11_113400106_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450932256 => 10_94937118_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444672993 => 7_87550285_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444694616 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/981202520 => 18_58149559_G_A
https://www.pharmgkb.org/clinicalAnnotation/655384616 => 5_75359673_T_G
https://www.pharmgkb.org/clinicalAnnotation/1449167512 => 4_3233253_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449168698 => 17_18264083_G_T
https://www.pharmgkb.org/clinicalAnnotation/637880014 => 7_87531302_A_T
https://www.pharmgkb.org/clinicalAnnotation/1446905703 => 20_3213247_A_C
https://www.pharmgkb.org/clinicalAnnotation/1450930827 => 15_78617110_T_C
https://www.pharmgkb.org/clinicalAnnotation/981204941 => 3_124737895_G_C
https://www.pharmgkb.org/clinicalAnnotation/1451126312 => 3_39492990_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447990235 => 10_94941958_T_C
https://www.pharmgkb.org/clinicalAnnotation/655386109 => 1_46813503_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449645561 => 16_30203612_G_T
https://www.pharmgkb.org/clinicalAnnotation/1444700550 => 16_31036758_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450936266 => 16_28606850_A_C
https://www.pharmgkb.org/clinicalAnnotation/1450928835 => 15_78559273_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451674148 => 19_40844679_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448820584 => 5_41142504_C_T
https://www.pharmgkb.org/clinicalAnnotation/1043880476 => 3_148742201_A_C
https://www.pharmgkb.org/clinicalAnnotation/1449188673 => 6_154027674_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444686857 => 2_233671246_A_C
https://www.pharmgkb.org/clinicalAnnotation/1183617623 => 15_74755085_T_C
https://www.pharmgkb.org/clinicalAnnotation/655384794 => 14_96204802_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447953102 => 16_79957795_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444607318 => 3_119806650_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449168712 => 17_18265930_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449270883 => 5_163486945_G_A
https://www.pharmgkb.org/clinicalAnnotation/981202562 => 10_94781859_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444704105 => 1_161544752_A_C
https://www.pharmgkb.org/clinicalAnnotation/1444699308 => MT_1494_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450928473 => 2_38075247_G_C
https://www.pharmgkb.org/clinicalAnnotation/1447960443 => 10_114045297_G_C
https://www.pharmgkb.org/clinicalAnnotation/1451637280 => 22_41993944_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448098304 => 3_119817582_G_A
https://www.pharmgkb.org/clinicalAnnotation/655385272 => 4_88134227_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451223580 => 8_28333789_A_C
https://www.pharmgkb.org/clinicalAnnotation/1444667668 => 1_78490747_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449003817 => 10_94942290_C_T
https://www.pharmgkb.org/clinicalAnnotation/655385223 => 7_128400698_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447982739 => 22_42127589_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451223520 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448102439 => 19_39244283_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447980875 => 22_42129770_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444673046 => 20_62216348_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449190422 => 11_113412966_C_A
https://www.pharmgkb.org/clinicalAnnotation/1446899702 => 4_21349637_T_C
https://www.pharmgkb.org/clinicalAnnotation/1183617765 => None
https://www.pharmgkb.org/clinicalAnnotation/1447986872 => 15_78590583_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449155302 => 7_75985688_C_T
https://www.pharmgkb.org/clinicalAnnotation/655385613 => 13_46837850_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451868520 => 10_119348388_G_A
https://www.pharmgkb.org/clinicalAnnotation/981202598 => 4_109912954_A_G
https://www.pharmgkb.org/clinicalAnnotation/655386310 => 3_179195218_C_A
https://www.pharmgkb.org/clinicalAnnotation/1183705773 => 19_38455359_A_C
https://www.pharmgkb.org/clinicalAnnotation/1451416400 => 13_46897343_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448109812 => 19_15906196_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183700891 => 11_27658369_C_T
https://www.pharmgkb.org/clinicalAnnotation/1445624605 => 6_160451754_C_G
https://www.pharmgkb.org/clinicalAnnotation/1450931447 => 19_3679742_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043873028 => 10_94935594_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449752810 => 6_32581698_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447962862 => 10_99804255_C_G
https://www.pharmgkb.org/clinicalAnnotation/655386665 => 19_45409478_C_A
https://www.pharmgkb.org/clinicalAnnotation/1449004876 => 21_45528653_G_A
https://www.pharmgkb.org/clinicalAnnotation/637879932 => 9_27536399_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448100296 => 10_94761288_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451397880 => 16_87855597_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183698841 => 5_132340627_C_T
https://www.pharmgkb.org/clinicalAnnotation/769171387 => 11_67585218_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043880039 => 22_19963748_G_A
https://www.pharmgkb.org/clinicalAnnotation/1184987404 => 20_59025600_G_C
https://www.pharmgkb.org/clinicalAnnotation/1184986623 => 2_233718962_T_G
https://www.pharmgkb.org/clinicalAnnotation/1451287240 => 1_97883329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451107360 => 5_148826910_G_C
https://www.pharmgkb.org/clinicalAnnotation/1449005031 => 7_99665212_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444680101 => 1_28848861_A_G

https://www.pharmgkb.org/clinicalAnnotation/1447946169 => 7_99767460_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450375752 => 4_88169725_T_C
https://www.pharmgkb.org/clinicalAnnotation/1444700958 => 12_32640040_G_A
https://www.pharmgkb.org/clinicalAnnotation/655384738 => 16_31094032_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449140069 => 3_119814886_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449168399 => 4_14788854_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451411555 => 22_24444708_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450811417 => 8_53251002_C_A
https://www.pharmgkb.org/clinicalAnnotation/655384626 => 12_21130388_G_A
https://www.pharmgkb.org/clinicalAnnotation/655385067 => 14_104803442_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449191373 => 7_117509035_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447987113 => 19_40851439_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449715928 => 7_87550285_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183618209 => 6_160139849_A_-
https://www.pharmgkb.org/clinicalAnnotation/1445401118 => 4_74556361_C_A
https://www.pharmgkb.org/clinicalAnnotation/1447981346 => 11_49164722_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451511240 => 9_127800446_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444607782 => 12_21178615_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451413082 => 1_162115895_G_T
https://www.pharmgkb.org/clinicalAnnotation/1043880438 => 2_233718890_C_A
https://www.pharmgkb.org/clinicalAnnotation/981204975 => 1_11796321_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451146241 => 10_111078003_C_T
https://www.pharmgkb.org/clinicalAnnotation/981239556 => 16_31094558_T_C
https://www.pharmgkb.org/clinicalAnnotation/1183693438 => 2_31365695_A_C
https://www.pharmgkb.org/clinicalAnnotation/1447946212 => 1_114693436_G_A
https://www.pharmgkb.org/clinicalAnnotation/1184748879 => 2_215340444_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183697531 => 21_45537880_T_C
https://www.pharmgkb.org/clinicalAnnotation/1450963060 => 19_45364001_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450929804 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449165230 => 6_160122116_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451437721 => MT_827_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448256091 => 6_42960723_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451245360 => 21_45537880_T_C
https://www.pharmgkb.org/clinicalAnnotation/1450934049 => 15_74749576_C_A
https://www.pharmgkb.org/clinicalAnnotation/1451286020 => 1_97305364_C_T
https://www.pharmgkb.org/clinicalAnnotation/655386995 => 7_99784473_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183564259 => 6_12296022_G_T
https://www.pharmgkb.org/clinicalAnnotation/1450812912 => 5_76968168_A_T
https://www.pharmgkb.org/clinicalAnnotation/1449168656 => 12_9657125_G_T
https://www.pharmgkb.org/clinicalAnnotation/1449753229 => 2_233757337_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451337885 => 8_18400285_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444665964 => 4_74556361_C_A
https://www.pharmgkb.org/clinicalAnnotation/1447981372 => 1_20601791_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444694562 => 1_206773062_T_G
https://www.pharmgkb.org/clinicalAnnotation/655386597 => 6_18138997_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444673156 => 1_161544752_A_C
https://www.pharmgkb.org/clinicalAnnotation/1444672986 => 11_116791691_G_C
https://www.pharmgkb.org/clinicalAnnotation/981240029 => 11_17388025_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449564196 => 6_44235246_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449182358 => 8_53251002_C_A
https://www.pharmgkb.org/clinicalAnnotation/1451403437 => 3_114136949_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450376443 => 16_55652906_T_A
https://www.pharmgkb.org/clinicalAnnotation/1451120960 => 12_99455122_G_T
https://www.pharmgkb.org/clinicalAnnotation/1183679818 => 1_97137438_A_G
https://www.pharmgkb.org/clinicalAnnotation/982030873 => 5_170788634_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448101086 => 6_160151834_C_A
https://www.pharmgkb.org/clinicalAnnotation/1450814929 => 9_8879118_C_T
https://www.pharmgkb.org/clinicalAnnotation/981202240 => None
https://www.pharmgkb.org/clinicalAnnotation/1451274200 => 1_97573943_C_A
https://www.pharmgkb.org/clinicalAnnotation/1447983818 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444666756 => 7_127524904_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444607803 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451131840 => 14_35405064_G_A
https://www.pharmgkb.org/clinicalAnnotation/981237871 => 12_20892760_A_G
https://www.pharmgkb.org/clinicalAnnotation/981237713 => 1_236885200_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451403580 => 6_88151570_G_C
https://www.pharmgkb.org/clinicalAnnotation/1446897675 => 7_87550285_A_G
https://www.pharmgkb.org/clinicalAnnotation/981238437 => 10_94981296_A_C
https://www.pharmgkb.org/clinicalAnnotation/1444701017 => 1_196185768_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447989803 => 18_661647_G_A
https://www.pharmgkb.org/clinicalAnnotation/982032228 => 11_27674363_C_A
https://www.pharmgkb.org/clinicalAnnotation/1448266838 => 7_99648291_A_G
https://www.pharmgkb.org/clinicalAnnotation/1140655380 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/655385997 => 10_97169185_A_G
https://www.pharmgkb.org/clinicalAnnotation/699642190 => 12_71958055_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447945850 => 7_87550493_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449166824 => 19_38442434_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451117560 => 2_164106976_T_C
https://www.pharmgkb.org/clinicalAnnotation/1183614687 => 13_105154672_C_A
https://www.pharmgkb.org/clinicalAnnotation/1450810247 => 6_154053957_C_A
https://www.pharmgkb.org/clinicalAnnotation/1448266413 => 3_119780660_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447963458 => 17_47733553_C_G
https://www.pharmgkb.org/clinicalAnnotation/1446899639 => 6_138830647_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449191424 => 7_117534363_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451244740 => 12_21178615_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447964236 => 4_61873823_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183700238 => 2_10123747_C_G
https://www.pharmgkb.org/clinicalAnnotation/1451127140 => 3_11259021_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451244800 => 12_21178615_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448124590 => 13_95210754_C_A
https://www.pharmgkb.org/clinicalAnnotation/1445400247 => 19_38500642_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451403608 => 3_114171968_C_T
https://www.pharmgkb.org/clinicalAnnotation/982031034 => 3_151338810_A_C
https://www.pharmgkb.org/clinicalAnnotation/1447990324 => 12_53430724_G_C
https://www.pharmgkb.org/clinicalAnnotation/1183614476 => 16_27344882_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448102368 => 12_111803962_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448097574 => 2_233682324_T_G
https://www.pharmgkb.org/clinicalAnnotation/1043859063 => 12_124863717_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451648440 => 9_133533736_C_A
https://www.pharmgkb.org/clinicalAnnotation/1448100103 => 1_109825608_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447986925 => 15_78623522_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444700867 => 12_47846052_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448614963 => 12_21334836_TTT_TTTT
https://www.pharmgkb.org/clinicalAnnotation/1043858661 => 1_203129147_T_G
https://www.pharmgkb.org/clinicalAnnotation/1450813869 => 6_18104864_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183960805 => 7_117534318_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449752825 => 6_32589759_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449144328 => 15_84137308_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451549101 => 18_673444_TTAAAGTTA_TTA
https://www.pharmgkb.org/clinicalAnnotation/1450934169 => 17_63943834_A_T
https://www.pharmgkb.org/clinicalAnnotation/1451476360 => 19_45420395_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448100354 => 12_21250045_T_C

https://www.pharmgkb.org/clinicalAnnotation/1444703739 => 13_46895805_G_A
https://www.pharmgkb.org/clinicalAnnotation/655385475 => 1_11794400_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451674220 => 19_40845322_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448100242 => 19_11132089_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448100235 => 3_133756878_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451106460 => 12_79430071_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451406860 => 16_53831818_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451135574 => 5_90730817_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449168378 => 3_21757936_T_C
https://www.pharmgkb.org/clinicalAnnotation/655386830 => 1_20604981_G_A
https://www.pharmgkb.org/clinicalAnnotation/637879987 => 9_27561051_T_C
https://www.pharmgkb.org/clinicalAnnotation/637880563 => 7_87516598_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183592332 => 10_113729830_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449157600 => 6_32223953_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444673084 => 5_132369766_C_G
https://www.pharmgkb.org/clinicalAnnotation/1451151857 => 13_46895805_G_A
https://www.pharmgkb.org/clinicalAnnotation/1043880608 => 12_21176804_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183615367 => 10_119080683_G_A
https://www.pharmgkb.org/clinicalAnnotation/1184513898 => 3_165829781_C_A
https://www.pharmgkb.org/clinicalAnnotation/1444700502 => 4_88121701_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447963688 => 1_46405089_C_A
https://www.pharmgkb.org/clinicalAnnotation/1448635176 => 13_48037847_G_C
https://www.pharmgkb.org/clinicalAnnotation/1183491775 => 1_11796321_G_A
https://www.pharmgkb.org/clinicalAnnotation/1184661194 => 19_15879621_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449162591 => 3_38142879_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447984146 => 7_87531302_A_C
https://www.pharmgkb.org/clinicalAnnotation/1183532599 => 12_124800202_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450811984 => 6_154106606_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447964331 => 7_45921476_G_T
https://www.pharmgkb.org/clinicalAnnotation/1451553602 => 4_88131171_G_T
https://www.pharmgkb.org/clinicalAnnotation/1451615920 => 8_11390991_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449296314 => 1_11796321_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448258734 => 12_21176804_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183697278 => 10_94988738_A_T
https://www.pharmgkb.org/clinicalAnnotation/1450936296 => 16_28608717_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447980897 => 7_117642566_G_A
https://www.pharmgkb.org/clinicalAnnotation/827847725 => 21_40043117_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448427833 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451148780 => 10_94949118_A_T
https://www.pharmgkb.org/clinicalAnnotation/655386661 => 19_45409478_C_A
https://www.pharmgkb.org/clinicalAnnotation/637879997 => 1_89384015_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449270985 => 19_7172515_C_A
https://www.pharmgkb.org/clinicalAnnotation/1449645420 => 16_30200747_A_C
https://www.pharmgkb.org/clinicalAnnotation/655384607 => 1_163063901_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183533592 => 5_75352778_A_T
https://www.pharmgkb.org/clinicalAnnotation/655384670 => 19_44908822_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444607634 => 6_160139813_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448112493 => 11_11458319_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451151522 => 16_24681727_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451244720 => 12_21178615_T_C
https://www.pharmgkb.org/clinicalAnnotation/1183620349 => X_154534419_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450826545 => 5_1393746_GTGGGGGCCCTGCATGCGTCCTGGGGTAGTACACGCTCCAGTGGGGGCCCTGCATGCGTCCTGGGGTAGTACACGCTCC_GTGGGGGCCCTGCATGCGTCCTGGGGTAGTACACGCTCCAGTGGGGGCCCTGCATGCGTCCTGGGGTAGTACACGCTCCAGTGGGGGCCCTGCATGCGTCCTGGGGTAGTACACGCTCC
https://www.pharmgkb.org/clinicalAnnotation/1445402163 => 1_209685108_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444704419 => 17_19560030_G_A
https://www.pharmgkb.org/clinicalAnnotation/1184987573 => 22_19963748_G_A
https://www.pharmgkb.org/clinicalAnnotation/619523400 => 11_4138227_A_G
https://www.pharmgkb.org/clinicalAnnotation/981204044 => 16_31096368_C_T
https://www.pharmgkb.org/clinicalAnnotation/981204107 => 1_186681189_C_G
https://www.pharmgkb.org/clinicalAnnotation/655384772 => 5_63962738_C_G
https://www.pharmgkb.org/clinicalAnnotation/1451118277 => 12_20020830_C_G
https://www.pharmgkb.org/clinicalAnnotation/1447980753 => 18_40449909_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444700536 => 11_62991327_C_G
https://www.pharmgkb.org/clinicalAnnotation/1451553580 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451350944 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1184472721 => 6_44233216_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451413120 => 1_162115895_G_T
https://www.pharmgkb.org/clinicalAnnotation/1449167093 => 20_64086577_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448100426 => 6_106207742_T_C
https://www.pharmgkb.org/clinicalAnnotation/1185000205 => 7_99672916_T_C
https://www.pharmgkb.org/clinicalAnnotation/1183632145 => 12_879392_C_T
https://www.pharmgkb.org/clinicalAnnotation/1446897666 => 13_28050157_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450375734 => 4_88099782_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444700423 => 6_160249250_A_C
https://www.pharmgkb.org/clinicalAnnotation/1448100158 => 8_66280144_T_C
https://www.pharmgkb.org/clinicalAnnotation/655384558 => 2_205787576_C_G
https://www.pharmgkb.org/clinicalAnnotation/1451217560 => 19_39248147_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444706818 => 9_4582843_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451678112 => 12_21178615_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448423689 => 2_203874196_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448530595 => X_49261784_G_T
https://www.pharmgkb.org/clinicalAnnotation/1449170150 => 6_31537703_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444706830 => 9_4586808_G_C
https://www.pharmgkb.org/clinicalAnnotation/1183491333 => 16_88646828_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448100777 => 12_47846052_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448125499 => 3_121924957_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448097805 => None
https://www.pharmgkb.org/clinicalAnnotation/1043858990 => 9_122370243_A_G
https://www.pharmgkb.org/clinicalAnnotation/1185000052 => 7_99672916_T_C
https://www.pharmgkb.org/clinicalAnnotation/1450933011 => 2_233728376_T_C
https://www.pharmgkb.org/clinicalAnnotation/981204466 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1445400945 => 7_150999023_T_G
https://www.pharmgkb.org/clinicalAnnotation/1447943673 => 12_6845711_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449575645 => 1_97234991_G_T
https://www.pharmgkb.org/clinicalAnnotation/1447961057 => 1_47377105_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451649200 => 10_5205821_C_G
https://www.pharmgkb.org/clinicalAnnotation/1448616900 => 6_43304450_A_G
https://www.pharmgkb.org/clinicalAnnotation/1446897184 => 2_112844982_A_G
https://www.pharmgkb.org/clinicalAnnotation/1142234402 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449155310 => 12_20858546_T_G
https://www.pharmgkb.org/clinicalAnnotation/1449167106 => 8_22927888_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447960204 => 5_148826910_G_C
https://www.pharmgkb.org/clinicalAnnotation/1449271393 => 22_40972293_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449168364 => 3_21757421_G_C
https://www.pharmgkb.org/clinicalAnnotation/1448100687 => 18_77256371_T_C
https://www.pharmgkb.org/clinicalAnnotation/1444843493 => 6_31498018_C_A
https://www.pharmgkb.org/clinicalAnnotation/1449575674 => 1_97593251_TTTT_TTT
https://www.pharmgkb.org/clinicalAnnotation/1183614624 => 2_166053034_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447962723 => 15_58431476_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451720988 => 3_31461468_C_T

https://www.pharmgkb.org/clinicalAnnotation/1449167228 => 16_4382028_A_T
https://www.pharmgkb.org/clinicalAnnotation/1184512433 => 9_127804260_A_G
https://www.pharmgkb.org/clinicalAnnotation/982032727 => 17_40098239_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451412140 => 1_45331833_C_G
https://www.pharmgkb.org/clinicalAnnotation/1447962855 => 7_87550285_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183630276 => 14_104793397_C_A
https://www.pharmgkb.org/clinicalAnnotation/1444700970 => 2_45828910_T_A
https://www.pharmgkb.org/clinicalAnnotation/655385139 => 11_17388025_T_C
https://www.pharmgkb.org/clinicalAnnotation/982032756 => 4_55435202_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448615589 => 10_94780653_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451118940 => 19_7522131_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449718277 => 10_99804058_G_A
https://www.pharmgkb.org/clinicalAnnotation/982045124 => 16_31093557_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449645432 => 16_30200753_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448097718 => 11_4099619_T_C
https://www.pharmgkb.org/clinicalAnnotation/981475450 => 7_55181378_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447681902 => 15_51266534_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451397780 => 16_87855597_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448259106 => 17_63476833_T_A
https://www.pharmgkb.org/clinicalAnnotation/1043858637 => 2_65069664_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450936183 => 16_28606092_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448100396 => 2_168532581_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451125520 => 6_30685004_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444673002 => 16_56870675_C_G
https://www.pharmgkb.org/clinicalAnnotation/1449270991 => 19_18120913_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451552587 => 19_41006936_G_T
https://www.pharmgkb.org/clinicalAnnotation/1183680656 => 7_75985688_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449164863 => 16_55662844_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451124808 => 20_56864307_C_T
https://www.pharmgkb.org/clinicalAnnotation/1296598910 => 22_46214170_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448532363 => 19_39252525_T_G
https://www.pharmgkb.org/clinicalAnnotation/1447949632 => 12_47863543_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444667305 => 7_87717503_G_T
https://www.pharmgkb.org/clinicalAnnotation/655386104 => 6_35385746_A_G
https://www.pharmgkb.org/clinicalAnnotation/1445401303 => 10_12690744_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451637220 => 22_41993944_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450826907 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1445594176 => 6_18130687_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451257700 => 5_7870860_A_G
https://www.pharmgkb.org/clinicalAnnotation/613979403 => 12_6845711_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183614825 => 2_233772770_T_C
https://www.pharmgkb.org/clinicalAnnotation/1445400917 => 9_133635393_T_C
https://www.pharmgkb.org/clinicalAnnotation/1448103942 => 15_78596058_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183631545 => 17_3563302_A_G
https://www.pharmgkb.org/clinicalAnnotation/1446908594 => 21_42232943_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448422839 => 19_41354391_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451141140 => 1_108937356_G_T
https://www.pharmgkb.org/clinicalAnnotation/1450931979 => 7_99763843_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444700999 => 14_96204802_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451151466 => 8_56512315_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451510621 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449645513 => 16_30201223_C_A
https://www.pharmgkb.org/clinicalAnnotation/1448100389 => 6_145701395_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451100100 => 7_99784473_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451125580 => 6_31575254_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451100053 => 5_174642665_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444666589 => 2_127260487_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447944819 => 4_122826931_C_T
https://www.pharmgkb.org/clinicalAnnotation/1446904604 => 14_64986345_G_C
https://www.pharmgkb.org/clinicalAnnotation/1444706154 => 12_21179489_G_A
https://www.pharmgkb.org/clinicalAnnotation/1184513893 => 3_165830222_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449168642 => 12_5918126_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444703076 => 10_94781859_G_A
https://www.pharmgkb.org/clinicalAnnotation/1449188679 => 6_154039373_G_T
https://www.pharmgkb.org/clinicalAnnotation/655385097 => 2_11750302_C_G
https://www.pharmgkb.org/clinicalAnnotation/1451125640 => 9_449798_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183612432 => 10_113729393_C_G
https://www.pharmgkb.org/clinicalAnnotation/1444700950 => 10_60794716_T_G
https://www.pharmgkb.org/clinicalAnnotation/1447964346 => 7_45937683_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448099080 => 11_85980619_G_C
https://www.pharmgkb.org/clinicalAnnotation/1451120724 => 18_12291681_T_G
https://www.pharmgkb.org/clinicalAnnotation/655385115 => 7_30678487_G_A
https://www.pharmgkb.org/clinicalAnnotation/981204864 => 1_11794419_T_G
https://www.pharmgkb.org/clinicalAnnotation/1043858722 => 1_156882671_A_C
https://www.pharmgkb.org/clinicalAnnotation/1444668236 => 12_53361428_A_G
https://www.pharmgkb.org/clinicalAnnotation/655384918 => 22_38067645_T_G
https://www.pharmgkb.org/clinicalAnnotation/1296599132 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449718242 => 2_38071060_G_C
https://www.pharmgkb.org/clinicalAnnotation/1448099059 => 1_213772666_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447960745 => 6_31144707_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444666571 => 15_74755085_T_C
https://www.pharmgkb.org/clinicalAnnotation/1183704282 => 5_56832039_G_A
https://www.pharmgkb.org/clinicalAnnotation/1446908002 => 19_40990556_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447982843 => 6_16161194_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444666738 => 18_58140841_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444706112 => 11_112155433_G_C
https://www.pharmgkb.org/clinicalAnnotation/1448632491 => 19_51235662_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448102324 => 11_112164265_C_G
https://www.pharmgkb.org/clinicalAnnotation/1183705817 => 19_38500654_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449157000 => 17_34285875_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444703529 => 15_40003758_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450930470 => 1_28863626_G_A
https://www.pharmgkb.org/clinicalAnnotation/1043880214 => None
https://www.pharmgkb.org/clinicalAnnotation/1447943685 => 12_6845711_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451637320 => 5_80184547_A_C
https://www.pharmgkb.org/clinicalAnnotation/1183614802 => 16_27325106_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447961122 => 7_125929387_C_T
https://www.pharmgkb.org/clinicalAnnotation/1043859386 => 2_233672032_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449645450 => 16_30200753_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448616381 => 17_75093757_T_C
https://www.pharmgkb.org/clinicalAnnotation/1447990143 => 10_94981296_A_C
https://www.pharmgkb.org/clinicalAnnotation/655384946 => 13_46895805_G_A
https://www.pharmgkb.org/clinicalAnnotation/1446906350 => 2_48962782_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447981465 => 5_6720954_A_G
https://www.pharmgkb.org/clinicalAnnotation/981201455 => 22_36700882_T_C
https://www.pharmgkb.org/clinicalAnnotation/1451397872 => 16_87855597_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444607611 => 22_42130692_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451674308 => 19_40846937_G_T
https://www.pharmgkb.org/clinicalAnnotation/1448100464 => 11_113414814_C_A
https://www.pharmgkb.org/clinicalAnnotation/1446902927 => 9_9687487_C_T
https://www.pharmgkb.org/clinicalAnnotation/1449165794 => 6_149400554_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448522760 => 5_56900777_G_A

https://www.pharmgkb.org/clinicalAnnotation/1449270937 => 10_95013625_G_A
https://www.pharmgkb.org/clinicalAnnotation/655385307 => 1_11796321_G_A
https://www.pharmgkb.org/clinicalAnnotation/1445401399 => 11_113400106_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183697557 => 1_20589038_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444705214 => 17_30237328_T_C
https://www.pharmgkb.org/clinicalAnnotation/1444704914 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451285000 => 12_47846052_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451476520 => 16_88646828_A_G
https://www.pharmgkb.org/clinicalAnnotation/1043880205 => 16_56962376_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450823785 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/655384914 => 4_186082920_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448109802 => 16_89549357_T_G
https://www.pharmgkb.org/clinicalAnnotation/1451416422 => 13_46895805_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450931410 => 19_3653527_C_T
https://www.pharmgkb.org/clinicalAnnotation/982031374 => 17_40096959_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444700488 => 4_88097526_A_C
https://www.pharmgkb.org/clinicalAnnotation/1447962613 => 1_213985913_T_C
https://www.pharmgkb.org/clinicalAnnotation/1183603016 => 3_45689959_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450373610 => 11_45674603_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447963227 => 11_113414814_C_A
https://www.pharmgkb.org/clinicalAnnotation/982032734 => 3_119912967_A_G
https://www.pharmgkb.org/clinicalAnnotation/1444668477 => 8_117172544_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450929031 => 12_118152057_T_C
https://www.pharmgkb.org/clinicalAnnotation/1184986454 => 6_31481199_C_A
https://www.pharmgkb.org/clinicalAnnotation/827848725 => 6_43436773_G_A
https://www.pharmgkb.org/clinicalAnnotation/1448097405 => 10_99782821_C_T
https://www.pharmgkb.org/clinicalAnnotation/1447981158 => 4_69094669_C_G
https://www.pharmgkb.org/clinicalAnnotation/1183624328 => 3_114160715_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183679808 => 18_51675444_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183680511 => 8_68476982_C_G
https://www.pharmgkb.org/clinicalAnnotation/1043859108 => 12_21178615_T_C
https://www.pharmgkb.org/clinicalAnnotation/1449716178 => 6_154112099_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450822829 => 5_131160322_C_T
https://www.pharmgkb.org/clinicalAnnotation/1448100313 => 4_69096892_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183615213 => 1_11796321_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183615415 => 12_6341779_T_C
https://www.pharmgkb.org/clinicalAnnotation/1043858980 => 17_4933086_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451125620 => 6_31760120_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451290960 => 11_17388025_T_C
https://www.pharmgkb.org/clinicalAnnotation/981201584 => 1_20589097_CCC_CC
https://www.pharmgkb.org/clinicalAnnotation/1184986763 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1450934656 => X_101407797_A_C
https://www.pharmgkb.org/clinicalAnnotation/982034400 => 5_170378952_C_G
https://www.pharmgkb.org/clinicalAnnotation/1448427972 => 9_84673278_G_T
https://www.pharmgkb.org/clinicalAnnotation/1444700445 => 6_111601300_G_C
https://www.pharmgkb.org/clinicalAnnotation/655385054 => 11_113400106_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447943713 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1448100340 => 7_99823462_G_A
https://www.pharmgkb.org/clinicalAnnotation/1450812241 => 6_154072545_T_C
https://www.pharmgkb.org/clinicalAnnotation/982034197 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451346385 => 16_55823658_C_T
https://www.pharmgkb.org/clinicalAnnotation/637879942 => 4_35370476_T_C
https://www.pharmgkb.org/clinicalAnnotation/1450826981 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/655387839 => 1_11794419_T_G
https://www.pharmgkb.org/clinicalAnnotation/1444703063 => 10_94781859_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444933020 => 19_41006936_G_T
https://www.pharmgkb.org/clinicalAnnotation/1183606395 => 12_2338248_G_C
https://www.pharmgkb.org/clinicalAnnotation/1444700495 => 4_88115014_C_G
https://www.pharmgkb.org/clinicalAnnotation/1183698868 => 2_233757013_T_G
https://www.pharmgkb.org/clinicalAnnotation/1450810283 => 6_154058017_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183630664 => 1_97515787_A_C
https://www.pharmgkb.org/clinicalAnnotation/1450928505 => 22_19963684_C_G
https://www.pharmgkb.org/clinicalAnnotation/982031013 => 12_107001328_A_G
https://www.pharmgkb.org/clinicalAnnotation/1185003565 => 1_161544752_A_C
https://www.pharmgkb.org/clinicalAnnotation/1444607751 => 19_43553422_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444673209 => 6_43770093_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449191752 => 7_117611663_T_A
https://www.pharmgkb.org/clinicalAnnotation/1447814185 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1449004239 => 3_116710060_C_A
https://www.pharmgkb.org/clinicalAnnotation/1449715913 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183703010 => 2_233718658_G_A
https://www.pharmgkb.org/clinicalAnnotation/1131245975 => 13_95044286_C_T
https://www.pharmgkb.org/clinicalAnnotation/1451254525 => 16_55823658_C_T
https://www.pharmgkb.org/clinicalAnnotation/1445401317 => 1_46413890_T_G
https://www.pharmgkb.org/clinicalAnnotation/1449270925 => 6_138132382_G_T
https://www.pharmgkb.org/clinicalAnnotation/981202366 => 8_63039169_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444700660 => 21_21768203_C_A
https://www.pharmgkb.org/clinicalAnnotation/1444843613 => 19_39241143_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183490978 => 11_113400106_G_A
https://www.pharmgkb.org/clinicalAnnotation/1451130528 => 10_99845936_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183700396 => 5_148826877_G_A
https://www.pharmgkb.org/clinicalAnnotation/1183632175 => 5_148826877_G_A
https://www.pharmgkb.org/clinicalAnnotation/1447990296 => 5_61302119_C_G
https://www.pharmgkb.org/clinicalAnnotation/1043880644 => 9_133279294_T_G
https://www.pharmgkb.org/clinicalAnnotation/1183698831 => 7_22727026_C_G
https://www.pharmgkb.org/clinicalAnnotation/1043880357 => 16_31087690_T_C
https://www.pharmgkb.org/clinicalAnnotation/1445401853 => 19_45420395_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451118960 => 19_7529361_C_A
https://www.pharmgkb.org/clinicalAnnotation/1451408008 => 22_19962712_C_T
https://www.pharmgkb.org/clinicalAnnotation/1184989651 => 6_32713272_A_C
https://www.pharmgkb.org/clinicalAnnotation/655385426 => 10_90834586_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450814923 => 3_12351626_C_G
https://www.pharmgkb.org/clinicalAnnotation/1183960795 => 7_117642451_G_A
https://www.pharmgkb.org/clinicalAnnotation/655386320 => 1_225838705_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451825200 => 6_154039662_A_G
https://www.pharmgkb.org/clinicalAnnotation/1447943608 => 7_87509329_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451125532 => 6_31117579_C_T
https://www.pharmgkb.org/clinicalAnnotation/1183960800 => 7_117642472_G_A
https://www.pharmgkb.org/clinicalAnnotation/1444704373 => 20_46448270_A_G
https://www.pharmgkb.org/clinicalAnnotation/1451504300 => 3_165830419_C_A
https://www.pharmgkb.org/clinicalAnnotation/1451150040 => 2_137506661_A_G
https://www.pharmgkb.org/clinicalAnnotation/1183705759 => 19_38444211_C_T
https://www.pharmgkb.org/clinicalAnnotation/655385400 => 19_15879621_C_T
https://www.pharmgkb.org/clinicalAnnotation/1043880426 => 3_47418189_C_T
https://www.pharmgkb.org/clinicalAnnotation/655384962 => 3_114171968_C_T
https://www.pharmgkb.org/clinicalAnnotation/1450814659 => 10_117264991_C_T
https://www.pharmgkb.org/clinicalAnnotation/1444700597 => 11_4094257_T_C
https://www.pharmgkb.org/clinicalAnnotation/1444705191 => 12_2207029_T_A

### Option 2

* Use `variants.tsv` for chrom & pos, otherwise parse from HGVS
* Which HGVS to use is the main issue, also weirdly indirect considering how usually well-defined rsids are
* Might generalise better to structural variants but likely not star alleles

In [62]:
variants[variants['Variant Name'].isin(('rs75527207', 'rs45445694'))]

,Variant ID,Variant Name,Gene IDs,Gene Symbols,Location,Variant Annotation count,Clinical Annotation count,Level 1/2 Clinical Annotation count,Guideline Annotation count,Label Annotation count,Synonyms
4437,PA166155331,rs45445694,"PA134956204,PA359","C18orf56,TYMS",NC_000018.10:657646_657712,87,7,0,0,1,"NC_000018.9:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[8], NG_028255.1:g.5054GGCCTGCCTCCGTCCCGCCGCGCCACTT[7], NC_000018.9:g.657646_657673CCGCGCCACTTGGCCTGCCTCCGTCCCG[2][3][4][7][8][9], NG_028255.1:g.5043_5109=, NG_028255.1:g.5054GGCCTGCCTCCGTCCCGCCGCGCCACTT[1], NC_000018.9:g.657646_657712=, NC_000018.9:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[4], NG_028255.1:g.5054GGCCTGCCTCCGTCCCGCCGCGCCACTT[3], TSER, NC_000018.10:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[7], NC_000018.10:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[1], NC_000018.10:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[3], XM_005258137.1:c.-97_-70CCGCGCCACTTGGCCTGCCTCCGTCCCG[2][3][4][7][8][9], NC_000018.10:g.657657_657712del, NC_000018.10:g.657646_657712=, NC_000018.9:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[9], NG_028255.1:g.5054GGCCTGCCTCCGTCCCGCCGCGCCACTT[9], NC_000018.10:g.657646_657673CCGCGCCACTTGGCCTGCCTCCGTCCCG[2][3][4][7][8][9], NG_028255.1:g.5054GGCCTGCCTCCGTCCCGCCGCGCCACTT[4], XM_005258138.1:c.-97_-70CCGCGCCACTTGGCCTGCCTCCGTCCCG[2][3][4][7][8][9], NC_000018.9:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[7], 45445694, NC_000018.9:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[1], NC_000018.9:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[3], NM_001071.2:c.-97_-70CCGCGCCACTTGGCCTGCCTCCGTCCCG[2][3][4][7][8][9], NC_000018.10:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[8], NG_028255.1:g.5054_5109del, NG_028255.1:g.5043_5070CCGCGCCACTTGGCCTGCCTCCGTCCCG[2][3][4][7][8][9], NC_000018.10:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[4], rs45445694, NC_000018.10:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[9], NC_000018.9:g.657657_657712del, NG_028255.1:g.5054GGCCTGCCTCCGTCCCGCCGCGCCACTT[8], NM_001012716.2:c.*34+169_*34+196CGGGACGGAGGCAGGCCAAGTGGCGCGG[2][3][4][7][8][9]"
5839,PA166157516,rs75527207,PA109,CFTR,NC_000007.14:117587806,32,2,1,1,1,"XM_011515754.1:c.1409G>A, XP_011514056.1:p.Gly470Asp, NG_056131.3:g.761G>A, NG_016465.4:g.127023G>A, NM_000492.3:c.1652G>A, XM_011515753.1:c.1409G>A, NP_000483.3:p.Gly551Asp, NC_000007.13:g.117227860=, NC_000007.14:g.117587806G>A, XM_011515752.1:c.1742G>A, XP_011514053.1:p.Gly581Asp, XP_011514055.1:p.Gly470Asp, 75527207, XM_011515751.1:c.1742G>A, XP_011514054.1:p.Gly581Asp, NC_000007.14:g.117587806=, NG_056131.1:g.130G>A, NG_016465.4:g.127023=, NC_000007.13:g.117227860G>A, rs75527207, NG_056131.1:g.130=, NP_000483.3:p.Gly551=, NG_056131.3:g.761="

In [1]:
from eva_cttv_pipeline.clinvar_xml_io.clinvar_xml_io.hgvs_variant import HgvsVariant, any_sequence_type_regex

In [8]:
h = HgvsVariant('NC_000007.14:g.117587806G>A')

In [9]:
h.start, h.stop, h.sequence_type, h.reference_sequence, h.ref, h.alt

(117587806, 117587806, <SequenceType.GENOMIC: 2>, 'NC_000007.14', 'G', 'A')

In [16]:
h2 = HgvsVariant('NC_000018.10:g.657657GGCCTGCCTCCGTCCCGCCGCGCCACTT[7]')

In [17]:
h2.start, h2.stop, h2.reference_sequence, h2.repeat_sequence

(657657, 657657, 'NC_000018.10', 'GGCCTGCCTCCGTCCCGCCGCGCCACTT')

In [18]:
h.variant_type

In [19]:
h2.variant_type

### Sample clinical annotation evidence string

In [68]:
clinical_annotations.loc[548]

Clinical Annotation ID                                                          1183679833
Variant/Haplotypes                                                              rs17376848
Gene                                                                                  DPYD
Level of Evidence                                                                       1A
Level Override                                                                         NaN
Level Modifiers                                                                 Tier 1 VIP
Score                                                                                 94.5
Phenotype Category                                                                Toxicity
PMID Count                                                                              11
Evidence Count                                                                          13
Drug(s)                                                                       fluorouracil
Phenotype(s)                                                                     Neoplasms
Latest History Date (YYYY-MM-DD)                                                2021-03-24
URL                                 https://www.pharmgkb.org/clinicalAnnotation/1183679833
Specialty Population                                                                   NaN
Name: 548, dtype: object

In [69]:
get_coordinates_for_clinical_annotation(1183679833)

'1_97450068_A_G'

In [ ]:
evidence_1183679833 = {
    'geneFromSourceId': 'ENSG00000188641', # still explode on these?
    'variantId': '1_97450068_A_G'
    'variantRsId': 'rs17376848',
    'variantFunctionalConsequence': ...,
    'variantOverlappingGeneId': ...,       # still explode on these?
    'drugId': 'CHEBI_46345',            # decided couldn't separate
    'pgxCategory': 'EFO_0020003',          # or "toxicity"?
    'capturedPhenotype': 'EFO_0000616', # decided couldn't separate
    'dataType': 'clinicalAnnotation',
    'evidenceLevel': '1A',
    'studyId': 1183679833,                 # clinical annotation id
    'datasourceId': 'pharmgkb',
    'datasourceVersion': '2022-09-13'      # file download date
}

In [71]:
clinical_annotations.iloc[570]

Clinical Annotation ID                                                                    1183680546
Variant/Haplotypes                                                                        rs12979860
Gene                                                                                     IFNL3;IFNL4
Level of Evidence                                                                                 1A
Level Override                                                                                   NaN
Level Modifiers                                                                                  NaN
Score                                                                                         213.25
Phenotype Category                                                                          Efficacy
PMID Count                                                                                         5
Evidence Count                                                                                     7
Drug(s)                             boceprevir;peginterferon alfa-2a;peginterferon alfa-2b;ribavirin
Phenotype(s)                                                                    Hepatitis C, Chronic
Latest History Date (YYYY-MM-DD)                                                          2021-03-24
URL                                           https://www.pharmgkb.org/clinicalAnnotation/1183680546
Specialty Population                                                                             NaN
Name: 570, dtype: object

In [72]:
get_coordinates_for_clinical_annotation(1183680546)

'19_39248147_C_T'

In [ ]:
evidence_1183680546 = {
    'geneFromSourceIds': ['IFNL3', 'IFNL4'], # NB
    'variantId': '19_39248147_C_T'
    'variantRsId': 'rs12979860',
    'variantFunctionalConsequence': ...,
    'variantOverlappingGeneId': ...,
    'drugIds': ['boceprevir', 'peginterferon alfa-2a', 'peginterferon alfa-2b', 'ribavirin'],  # NB - explode OK as long as we also provide clinical annotation ID
    'pgxCategory': 'efficacy',
    'capturedPhenotypes': ['hepatitis C'],
    'dataType': 'clinicalAnnotation',
    'evidenceLevel': '1A',
    'underlyingEvidence': ...,
    'datasourceId': 'pharmgkb',
    'datasourceVersion': '2022-09-13'
}

In [81]:
clinical_annotations.set_index('Clinical Annotation ID').index.is_unique

True

In [82]:
clinical_annotations

,Clinical Annotation ID,Variant/Haplotypes,Gene,Level of Evidence,Level Override,Level Modifiers,Score,Phenotype Category,PMID Count,Evidence Count,Drug(s),Phenotype(s),Latest History Date (YYYY-MM-DD),URL,Specialty Population
0,981755803,rs75527207,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,234.8750,Efficacy,28,30,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981755803,Pediatric
1,1449311190,rs4149056,SLCO1B1,3,NaN,Tier 1 VIP,2.0000,Dosage,1,1,mercaptopurine;methotrexate,Precursor Cell Lymphoblastic Leukemia-Lymphoma,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449311190,Pediatric
2,981204774,rs1799971,OPRM1,4,NaN,NaN,-2.0000,Efficacy,2,3,Drugs used in nicotine dependence;nicotine,Tobacco Use Disorder,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981204774,NaN
3,1449191690,rs141033578,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,200.0000,Efficacy,1,3,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449191690,NaN
4,1449191746,rs78769542,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,200.0000,Efficacy,1,3,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449191746,NaN
5,981419532,rs4693075,COQ2,3,NaN,NaN,3.2500,Toxicity,3,3,atorvastatin;hmg coa reductase inhibitors;rosuvastatin,Muscular Diseases,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981419532,NaN
6,1449566379,rs11065987,NaN,3,NaN,NaN,2.5000,Efficacy,1,1,hydrochlorothiazide,Hypertension,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449566379,NaN
7,981419266,HLA-B*15:02:01,HLA-B,1A,NaN,Tier 1 VIP,315.7500,Toxicity,18,23,phenytoin,"drug reaction with eosinophilia and systemic symptoms;Epidermal Necrolysis, Toxic;severe cutaneous adverse reactions;Stevens-Johnson Syndrome",2022-06-22,https://www.pharmgkb.org/clinicalAnnotation/981419266,Pediatric
8,1451259580,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*10, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,211.3750,Toxicity,6,9,amitriptyline,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451259580,NaN
9,1451265560,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2xN, CYP2D6*4, CYP2D6*5",CYP2D6,1A,NaN,Tier 1 VIP,208.1250,Dosage,3,6,imipramine,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451265560,NaN
10,1451288200,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*2xN",CYP2D6,1A,NaN,Tier 1 VIP,203.6250,Toxicity,8,11,codeine,Pain,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451288200,Pediatric
11,1451282240,"CYP2D6*1, CYP2D6*3, CYP2D6*4, CYP2D6*4xN, CYP2D6*5, CYP2D6*6",CYP2D6,1A,NaN,Tier 1 VIP,201.7500,Toxicity,2,4,atomoxetine,Attention Deficit Disorder with Hyperactivity,2021-04-29,https://www.pharmgkb.org/clinicalAnnotation/1451282240,NaN
12,1451285240,"CYP2D6*1, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*7, CYP2D6*9, CYP2D6*10, CYP2D6*10x2, CYP2D6*11, CYP2D6*17, CYP2D6*21, CYP2D6*36, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,226.5625,Efficacy,56,143,tamoxifen,Breast Neoplasms,2021-04-29,https://www.pharmgkb.org/clinicalAnnotation/1451285240,NaN
13,1451226160,rs4680,COMT,3,NaN,Tier 1 VIP,2.2500,Toxicity,2,3,methadone,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226160,Pediatric
14,1451226166,rs4680,COMT,3,NaN,Tier 1 VIP,0.0000,Toxicity,1,1,methadone,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226166,NaN
15,1451226200,rs4732636,PNOC,3,NaN,NaN,0.0000,Toxicity,1,1,buprenorphine,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226200,Pediatric
16,1451226206,rs4732636,PNOC,3,NaN,NaN,0.0000,Toxicity,1,1,methadone,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226206,Pediatric
17,1451226212,rs740603,COMT,3,NaN,Tier 1 VIP,0.0000,Toxicity,1,1,buprenorphine,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226212,NaN
18,1451226220,rs740603,COMT,3,NaN,Tier 1 VIP,0.0000,Toxicity,1,1,methadone,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226220,NaN
19,1451340300,"UGT1A3*1, UGT1A3*2, UGT1A3*3",UGT1A3,3,NaN,NaN,4.0000,Metabolism/PK,1,2,telmisartan,NaN,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451340300,NaN
20,1451340320,rs60140950,SLCO1B3,3,NaN,NaN,1.5000,Metabolism/PK,1,1,telmisartan,NaN,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451340320,NaN
21,1450930839,rs1948,CHRNB4,3,NaN,NaN,3.0000,Toxicity,1,1,nicotine,Tobacco Use Disorder,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1450930839,NaN
22,1451356840,rs696,NFKBIA,3,NaN,NaN,1.7500,Dosage,1,1,sufentanil,"Pain, Postoperative",2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451356840,NaN
23,1451225360,rs4680,COMT,3,NaN,Tier 1 VIP,2.5000,Toxicity,1,2,buprenorphine,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451225360,Pediatric
24,1450930464,rs16917234,BDNF;BDNF-AS,3,NaN,NaN,2.2500,Other,1,1,heroin,Heroin Dependence,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1450930464,NaN
25,1451290960,rs5219,KCNJ11,3,NaN,NaN,3.7500,Efficacy,2,2,gliclazide,Diabetes Mellitus,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451290960,NaN
26,1451356520,rs4149056,SLCO1B1,3,NaN,Tier 1 VIP,2.2500,Efficacy,11,12,simvastatin,NaN,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451356520,NaN
27,655386913,"CYP2C19*1, CYP2C19*17",CYP2C19,3,NaN,Tier 1 VIP,6.0000,Toxicity,15,16,clopidogrel,Acute coronary syndrome;Coronary Artery Disease;Hemorrhage;Myocardial Infarction,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/655386913,NaN
28,1451356180,rs28379954,NFIB,3,NaN,NaN,0.0000,Metabolism/PK,1,1,clozapine,Schizophrenia,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451356180,NaN
29,1451151506,rs61974485,ARID4A,3,NaN,NaN,1.5000,Toxicity,1,1,ethanol,Alcoholism,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451151506,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4983,1451266020,rs55886062,DPYD,1A,NaN,Rare Variant; Tier 1 VIP,102.2500,Toxicity,2,3,tegafur,Neoplasms,2021-05-24,https://www.pharmgkb.org/clinicalAnnotation/1451266020,NaN
4984,1451257700,rs1801394,MTRR,3,NaN,NaN,4.7500,Efficacy,3,3,methotrexate,"Arthritis, Juvenile Rheumatoid;Arthritis, Rheumatoid",2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451257700,Pediatric
4985,1451263060,rs78132896,EPHA7,3,NaN,NaN,1.6250,Toxicity,1,1,warfarin,Hemorrhage,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451263060,NaN
4986,1183680656,rs1057868,POR,4,NaN,NaN,-0.5000,Toxicity,3,3,tacrolimus,Kidney Transplantation,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1183680656,Pediatric
4987,1451257285,"CYP2C8*1, CYP2C8*3",CYP2C8,3,NaN,Tier 1 VIP,4.5000,Efficacy,3,3,rosiglitazone,NaN,2021-12-03,https://www.pharmgkb.org/clinicalAnnotation/1451257285,NaN
4988,1451285000,rs1544410,VDR,3,NaN,NaN,2.7500,Efficacy,1,1,clodronate,NaN,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451285000,NaN
4989,1451256440,rs3813929,HTR2C,3,NaN,NaN,2.7500,Toxicity,11,11,olanzapine,Mental Disorders;Schizophrenia,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451256440,NaN
4990,1451256448,rs3813929,HTR2C,3,NaN,NaN,4.0000,Toxicity,8,8,risperidone,Mental Disorders;Schizophrenia,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451256448,Pediatric
4991,1451256466,rs3813929,HTR2C,3,NaN,NaN,3.0000,Toxicity,5,5,clozapine,Mental Disorders;Schizophrenia,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451256466,NaN
4992,1451274840,rs1059513,STAT6,3,NaN,NaN,2.2500,Efficacy,1,1,esomeprazole,eosinophilic esophagitis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451274840,Pediatric
4993,1451282140,rs4646,CYP19A1,3,NaN,NaN,5.0000,Efficacy,2,2,tamoxifen,Breast Neoplasms,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451282140,NaN
4994,1451286280,"CYP3A5*1, CYP3A5*3",CYP3A5,3,NaN,Tier 1 VIP,4.2500,Dosage,2,2,sirolimus,NaN,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451286280,NaN
4995,1451204660,"UGT1A1*1, UGT1A1*28",UGT1A1,1A,NaN,Tier 1 VIP,224.0000,Toxicity,33,40,FOLFIRI;irinotecan,Neutropenia,2021-04-01,https://www.pharmgkb.org/clinicalAnnotation/1451204660,Pediatric
4996,1451243980,"CYP2B6*1, CYP2B6*2, CYP2B6*6, CYP2B6*18, CYP2B6*38",CYP2B6,1A,NaN,Tier 1 VIP,211.5000,Toxicity,12,14,efavirenz,HIV Infections,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451243980,NaN
4997,1451551426,rs11615,ERCC1,3,NaN,NaN,1.7500,Efficacy,1,1,cisplatin;gemcitabine,"Carcinoma, Non-Small-Cell Lung",2021-10-20,https://www.pharmgkb.org/clinicalAnnotation/1451551426,NaN
4998,1451551460,rs11615,ERCC1,3,NaN,NaN,0.0000,Efficacy,1,1,cisplatin,Pancreatic Neoplasms,2021-10-20,https://www.pharmgkb.org/clinicalAnnotation/1451551460,NaN
4999,1450813831,rs746071566,NUDT15,3,NaN,Rare Variant; Tier 1 VIP,4.0000,Toxicity,1,1,azathioprine;mercaptopurine;thioguanine,Inflammatory Bowel Diseases;Myelosuppression,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1450813831,NaN
5000,1451135100,rs1799971,OPRM1,3,NaN,NaN,1.2500,Efficacy,2,2,oxycodone,NaN,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451135100,NaN
5001,1451289660,rs59086055,DPYD,1A,NaN,Rare Variant; Tier 1 VIP,100.0000,Toxicity,1,2,fluorouracil,Neoplasms,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451289660,NaN
5002,1451551520,rs3212986,ERCC1,4,NaN,NaN,-1.2500,Efficacy,3,3,cisplatin,Esophageal Neoplasms;Ovarian Neoplasms;Stomach Neoplasms,2021-10-20,https://www.pharmgkb.org/clinicalAnnotation/1451551520,NaN
5003,1451551528,rs2336219,ERCC1,3,NaN,NaN,0.0000,Efficacy,1,1,cisplatin,Ovarian Neoplasms,2021-10-20,https://www.pharmgkb.org/clinicalAnnotation/1451551528,NaN
5004,1451551846,rs11545077,GGH,3,NaN,NaN,2.5000,Efficacy,1,1,methotrexate,Precursor Cell Lymphoblastic Leukemia-Lymphoma,2021-10-20,https://www.pharmgkb.org/clinicalAnnotation/1451551846,Pediatric
5005,1451551817,rs3758149,GGH,3,NaN,NaN,2.5000,Efficacy,1,1,methotrexate,Precursor Cell Lymphoblastic Leukemia-Lymphoma,2021-10-20,https://www.pharmgkb.org/clinicalAnnotation/1451551817,Pediatric
5006,1451551883,rs11545076,GGH,3,NaN,NaN,2.5000,Efficacy,1,1,methotrexate,Precursor Cell Lymphoblastic Leukemia-Lymphoma,2021-10-20,https://www.pharmgkb.org/clinicalAnnotation/1451551883,Pediatric
5007,1451552587,rs3745274,CYP2A7P1;CYP2B6,3,NaN,Tier 1 VIP,1.0000,Metabolism/PK,1,1,tramadol,NaN,2021-10-21,https://www.pharmgkb.org/clinicalAnnotation/1451552587,NaN
5008,1451553326,rs45445694,C18orf56;TYMS,4,NaN,Tier 1 VIP,-1.0000,Metabolism/PK,2,2,methotrexate,Precursor Cell Lymphoblastic Leukemia-Lymphoma,2021-10-21,https://www.pharmgkb.org/clinicalAnnotation/1451553326,Pediatric
5009,1451553595,rs1045642,ABCB1,4,NaN,Tier 1 VIP,-1.2500,Efficacy,2,3,methotrexate,Precursor Cell Lymphoblastic Leukemia-Lymphoma,2021-10-21,https://www.pharmgkb.org/clinicalAnnotation/1451553595,Pediatric
5010,1451553580,rs1045642,ABCB1,3,NaN,Tier 1 VIP,0.0000,Metabolism/PK,5,5,methotrexate,"Burkitt Lymphoma;Lymphoma, T-Cell;Precursor Cell Lymphoblastic Leukemia-Lymphoma",2021-12-13,https://www.pharmgkb.org/clinicalAnnotation/1451553580,Pediatric
5011,1451566760,rs1800497,ANKK1;DRD2,3,NaN,Tier 1 VIP,1.5000,Efficacy,1,1,bupropion;naltrexone,Obesity,2021-10-29,https://www.pharmgkb.org/clinicalAnnotation/1451566760,NaN
5012,1451567040,"CYP3A4*1, CYP3A4*2, CYP3A4*3, CYP3A4*4, CYP3A4*5, CYP3A4*6, CYP3A4*7, CYP3A4*8, CYP3A4*9, CYP3A4*10, CYP3A4*11, CYP3A4*12, CYP3A4*13, CYP3A4*14, CYP3A4*15, CYP3A4*16, CYP3A4*17, CYP3A4*18, CYP3A4*19, CYP3A4*20, CYP3A4*21, CYP3A4*22, CYP3A4*23, CYP3A4*24, CYP3A4*26, CYP3A4*28, CYP3A4*29, CYP3A4*30, CYP3A4*31, CYP3A4*32, CYP3A4*33, CYP3A4*34",CYP3A4,3,NaN,Tier 1 VIP,2.5000,Metabolism/PK,2,3,oxycodone,NaN,2022-01-13,https://www.pharmgkb.org/clinicalAnnotation/1451567040,NaN

In [84]:
clinical_ann_alleles

,Clinical Annotation ID,Genotype/Allele,Annotation Text,Allele Function
0,981755803,AA,"Patients with the rs75527207 AA genotype (two copies of the CFTR G551D variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
1,981755803,AG,"Patients with the rs75527207 AG genotype (one copy of the CFTR G551D variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
2,981755803,GG,"Patients with the rs75527207 GG genotype (do not have a copy of the CFTR G551D variant) and cystic fibrosis have an unknown response to ivacaftor treatment, as response may depend on the presence of other CFTR variants. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
3,1449311190,CC,"Patients with the CC genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need a decreased dose of mercaptopurine, or methotrexate, as compared to children with the TT genotype. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.",NaN
4,1449311190,CT,"Patients with the CT genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need a decreased dose of mercaptopurine, or methotrexate, as compared to children with the TT genotype. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.",NaN
5,1449311190,TT,"Patients with the TT genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need an increased dose of mercaptopurine, or methotrexate, as compared to children with the CC or CT genotypes. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.",NaN
6,981204774,AA,"Patients with AA genotype may have an increased likelihood of smoking cessation when treated with nicotine replacement therapy (transdermal nicotine patch) as compared to patients with the AG and GG genotype. However, contradictory findings reporting the opposite association for this genotype with decreased likelihood of smoking cessation have been published. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation.",NaN
7,981204774,AG,"Patients with AG genotype may have a decreased likelihood of smoking cessation when treated with nicotine replacement therapy (transdermal nicotine patch) as compared to patients with the AA genotype. However, contradictory findings reporting the opposite association for this genotype with increased likelihood of smoking cessation have been published. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation.",NaN
8,981204774,GG,"Patients with GG genotype may have a decreased likelihood of smoking cessation when treated with nicotine replacement therapy (transdermal nicotine patch) as compared to patients with the AA genotype. However, contradictory findings reporting the opposite association for this genotype with increased likelihood of smoking cessation have been published. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation.",NaN
9,1449191690,CC,"Patients with the CC genotype (do not have a copy of the CFTR S977F variant) and cystic fibrosis have an unknown response to ivacaftor treatment, as response may depend on the presence of other CFTR variants. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including S977F. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
10,1449191690,CT,"Patients with the CT genotype (one copy of the CFTR S977F variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including S977F. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
11,1449191690,TT,"Patients with the TT genotype (two copies of the CFTR S977F variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including S977F. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
12,1449191746,AA,"Patients with the AA genotype (two copies of the CFTR R1070Q variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including R1070Q. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
13,1449191746,AG,"Patients with the AG genotype (one copy of the CFTR R1070Q variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including R1070Q. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
14,1449191746,GG,"Patients with the GG genotype (do not have a copy of the CFTR R1070Q variant) and cystic fibrosis have an unknown response to ivacaftor treatment, as response may depend on the presence of other CFTR variants. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including R1070Q. Other genetic and clinical factors may also influence response to ivacaftor.",NaN
15,981419532,CC,Patients with the CC genotype may have decreased risk of statin-related muscle symptoms as compared to patients with genotype GG or CG. Other genetic and clinical factors may also influence a patient's risk of toxicity.,NaN
16,981419532,CG,Patients with the CG genotype may have increased risk of statin-related muscle symptoms as compared to patients with genotype CC. Other genetic and clinical factors may also influence a patient's risk of toxicity.,NaN
17,981419532,GG,Patients with the GG genotype may have increased risk of statin-related muscle symptoms as compared to patients with genotype CC. Other genetic and clinical factors may also influence a patient's risk of toxicity.,NaN
18,1449566379,AA,"Patients with the AA genotype and hypertension may have an increased response to hydrochlorothiazide treatment, as measured by decreases in systolic and diastolic blood pressure, as compared to patients with the AG or GG genotypes. Other genetic and clinical factors may also affect a patient's response to hydrochlorothiazide.",NaN
19,1449566379,AG,"Patients with the AG genotype and hypertension may have an increased response to hydrochlorothiazide treatment, as measured by decreases in systolic and diastolic blood pressure, as compared to patients with the GG genotype, but a decreased response as compared to patients with the AA genotype. Other genetic and clinical factors may also affect a patient's response to hydrochlorothiazide.",NaN
20,1449566379,GG,"Patients with the GG genotype and hypertension may have a decreased response to hydrochlorothiazide treatment, as measured by decreases in systolic and diastolic blood pressure, as compared to patients with the AA or AG genotypes. Other genetic and clinical factors may also affect a patient's response to hydrochlorothiazide.",NaN
21,981419266,*15:02:01,"Patients with one or two copies of the HLA-B*15:02:01 allele may have an increased risk of Severe Cutaneous Adverse Reactions, such as Stevens-Johnson Syndrome and Toxic Epidermal Necrolysis, when treated with phenytoin as compared to patients with no HLA-B*15:02:01 alleles or negative for the HLA-B*15:02:01 test. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence risk of phenytoin-induced adverse reactions.",Presence
22,1451259580,*1,The CYP2D6*1 allele is assigned as a normal function allele by CPIC. Patients carrying the CYP2D6*1 allele in combination with alleles that result in a normal metabolizer phenotype who are treated with amitriptyline may have decreased likelihood of side effects as compared to patients with a combination of alleles that result in intermediate or poor metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,Normal function
23,1451259580,*1xN,The CYP2D6*1xN alleles (*1x2 and *1x≥3) have been assigned as increased function alleles by CPIC. Patients carrying the CYP2D6*1xN allele in combination with alleles that result in a normal metabolizer phenotype who are treated with amitriptyline may have decreased likelihood of side effects as compared to patients with a combination of alleles that result in intermediate or poor metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,Increased function
24,1451259580,*2,The CYP2D6*2 allele is assigned as a normal function allele by CPIC. Patients carrying the CYP2D6*2 allele in combination with alleles that result in a normal metabolizer phenotype who are treated with amitriptyline may have decreased likelihood of side effects as compared to patients with a combination of alleles that result in intermediate or poor metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,Normal function
25,1451259580,*3,The CYP2D6*3 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*3 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,No function
26,1451259580,*4,The CYP2D6*4 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*4 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,No function
27,1451259580,*5,The CYP2D6*5 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*5 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,No function
28,1451259580,*6,The CYP2D6*6 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*6 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,No function
29,1451259580,*10,The CYP2D6*10 allele is assigned as a decreased function allele with an activity value of 0.25 by CPIC. Patients carrying the CYP2D6*10 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,Decreased function (AV 0.25)
...,...,...,...,...
15456,1451567040,*3,Patients carrying the CYP3A4*3 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15457,1451567040,*4,Patients carrying the CYP3A4*4 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15458,1451567040,*5,Patients carrying the CYP3A4*5 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15459,1451567040,*6,Patients carrying the CYP3A4*6 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15460,1451567040,*7,Patients carrying the CYP3A4*7 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15461,1451567040,*8,Patients carrying the CYP3A4*8 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15462,1451567040,*9,Patients carrying the CYP3A4*9 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15463,1451567040,*10,Patients carrying the CYP3A4*10 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15464,1451567040,*11,Patients carrying the CYP3A4*11 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15465,1451567040,*12,Patients carrying the CYP3A4*12 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15466,1451567040,*13,Patients carrying the CYP3A4*13 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15467,1451567040,*14,Patients carrying the CYP3A4*14 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15468,1451567040,*15,Patients carrying the CYP3A4*15 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15469,1451567040,*16,Patients carrying the CYP3A4*16 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15470,1451567040,*17,Patients carrying the CYP3A4*17 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15471,1451567040,*18,Patients carrying the CYP3A4*18 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15472,1451567040,*19,Patients carrying the CYP3A4*19 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
15473,1451567040,*20,Patients carrying the CYP3A4*20 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN

In [86]:
clinical_annotations.join(clinical_ann_alleles, on='Clinical Annotation ID', how='outer', lsuffix='clinann')

,Clinical Annotation IDclinann,Variant/Haplotypes,Gene,Level of Evidence,Level Override,Level Modifiers,Score,Phenotype Category,PMID Count,Evidence Count,Drug(s),Phenotype(s),Latest History Date (YYYY-MM-DD),URL,Specialty Population,Clinical Annotation ID,Genotype/Allele,Annotation Text,Allele Function
0.0,9.817558e+08,rs75527207,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,234.8750,Efficacy,28.0,30.0,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981755803,Pediatric,981755803,NaN,NaN,NaN
1.0,1.449311e+09,rs4149056,SLCO1B1,3,NaN,Tier 1 VIP,2.0000,Dosage,1.0,1.0,mercaptopurine;methotrexate,Precursor Cell Lymphoblastic Leukemia-Lymphoma,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449311190,Pediatric,1449311190,NaN,NaN,NaN
2.0,9.812048e+08,rs1799971,OPRM1,4,NaN,NaN,-2.0000,Efficacy,2.0,3.0,Drugs used in nicotine dependence;nicotine,Tobacco Use Disorder,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981204774,NaN,981204774,NaN,NaN,NaN
3.0,1.449192e+09,rs141033578,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,200.0000,Efficacy,1.0,3.0,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449191690,NaN,1449191690,NaN,NaN,NaN
4.0,1.449192e+09,rs78769542,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,200.0000,Efficacy,1.0,3.0,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449191746,NaN,1449191746,NaN,NaN,NaN
5.0,9.814195e+08,rs4693075,COQ2,3,NaN,NaN,3.2500,Toxicity,3.0,3.0,atorvastatin;hmg coa reductase inhibitors;rosuvastatin,Muscular Diseases,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981419532,NaN,981419532,NaN,NaN,NaN
6.0,1.449566e+09,rs11065987,NaN,3,NaN,NaN,2.5000,Efficacy,1.0,1.0,hydrochlorothiazide,Hypertension,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449566379,NaN,1449566379,NaN,NaN,NaN
7.0,9.814193e+08,HLA-B*15:02:01,HLA-B,1A,NaN,Tier 1 VIP,315.7500,Toxicity,18.0,23.0,phenytoin,"drug reaction with eosinophilia and systemic symptoms;Epidermal Necrolysis, Toxic;severe cutaneous adverse reactions;Stevens-Johnson Syndrome",2022-06-22,https://www.pharmgkb.org/clinicalAnnotation/981419266,Pediatric,981419266,NaN,NaN,NaN
8.0,1.451260e+09,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*10, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,211.3750,Toxicity,6.0,9.0,amitriptyline,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451259580,NaN,1451259580,NaN,NaN,NaN
9.0,1.451266e+09,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2xN, CYP2D6*4, CYP2D6*5",CYP2D6,1A,NaN,Tier 1 VIP,208.1250,Dosage,3.0,6.0,imipramine,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451265560,NaN,1451265560,NaN,NaN,NaN
10.0,1.451288e+09,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*2xN",CYP2D6,1A,NaN,Tier 1 VIP,203.6250,Toxicity,8.0,11.0,codeine,Pain,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451288200,Pediatric,1451288200,NaN,NaN,NaN
11.0,1.451282e+09,"CYP2D6*1, CYP2D6*3, CYP2D6*4, CYP2D6*4xN, CYP2D6*5, CYP2D6*6",CYP2D6,1A,NaN,Tier 1 VIP,201.7500,Toxicity,2.0,4.0,atomoxetine,Attention Deficit Disorder with Hyperactivity,2021-04-29,https://www.pharmgkb.org/clinicalAnnotation/1451282240,NaN,1451282240,NaN,NaN,NaN
12.0,1.451285e+09,"CYP2D6*1, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*7, CYP2D6*9, CYP2D6*10, CYP2D6*10x2, CYP2D6*11, CYP2D6*17, CYP2D6*21, CYP2D6*36, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,226.5625,Efficacy,56.0,143.0,tamoxifen,Breast Neoplasms,2021-04-29,https://www.pharmgkb.org/clinicalAnnotation/1451285240,NaN,1451285240,NaN,NaN,NaN
13.0,1.451226e+09,rs4680,COMT,3,NaN,Tier 1 VIP,2.2500,Toxicity,2.0,3.0,methadone,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226160,Pediatric,1451226160,NaN,NaN,NaN
14.0,1.451226e+09,rs4680,COMT,3,NaN,Tier 1 VIP,0.0000,Toxicity,1.0,1.0,methadone,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226166,NaN,1451226166,NaN,NaN,NaN
15.0,1.451226e+09,rs4732636,PNOC,3,NaN,NaN,0.0000,Toxicity,1.0,1.0,buprenorphine,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226200,Pediatric,1451226200,NaN,NaN,NaN
16.0,1.451226e+09,rs4732636,PNOC,3,NaN,NaN,0.0000,Toxicity,1.0,1.0,methadone,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226206,Pediatric,1451226206,NaN,NaN,NaN
17.0,1.451226e+09,rs740603,COMT,3,NaN,Tier 1 VIP,0.0000,Toxicity,1.0,1.0,buprenorphine,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226212,NaN,1451226212,NaN,NaN,NaN
18.0,1.451226e+09,rs740603,COMT,3,NaN,Tier 1 VIP,0.0000,Toxicity,1.0,1.0,methadone,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451226220,NaN,1451226220,NaN,NaN,NaN
19.0,1.451340e+09,"UGT1A3*1, UGT1A3*2, UGT1A3*3",UGT1A3,3,NaN,NaN,4.0000,Metabolism/PK,1.0,2.0,telmisartan,NaN,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451340300,NaN,1451340300,NaN,NaN,NaN
20.0,1.451340e+09,rs60140950,SLCO1B3,3,NaN,NaN,1.5000,Metabolism/PK,1.0,1.0,telmisartan,NaN,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451340320,NaN,1451340320,NaN,NaN,NaN
21.0,1.450931e+09,rs1948,CHRNB4,3,NaN,NaN,3.0000,Toxicity,1.0,1.0,nicotine,Tobacco Use Disorder,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1450930839,NaN,1450930839,NaN,NaN,NaN
22.0,1.451357e+09,rs696,NFKBIA,3,NaN,NaN,1.7500,Dosage,1.0,1.0,sufentanil,"Pain, Postoperative",2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451356840,NaN,1451356840,NaN,NaN,NaN
23.0,1.451225e+09,rs4680,COMT,3,NaN,Tier 1 VIP,2.5000,Toxicity,1.0,2.0,buprenorphine,Neonatal Abstinence Syndrome,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451225360,Pediatric,1451225360,NaN,NaN,NaN
24.0,1.450930e+09,rs16917234,BDNF;BDNF-AS,3,NaN,NaN,2.2500,Other,1.0,1.0,heroin,Heroin Dependence,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1450930464,NaN,1450930464,NaN,NaN,NaN
25.0,1.451291e+09,rs5219,KCNJ11,3,NaN,NaN,3.7500,Efficacy,2.0,2.0,gliclazide,Diabetes Mellitus,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451290960,NaN,1451290960,NaN,NaN,NaN
26.0,1.451357e+09,rs4149056,SLCO1B1,3,NaN,Tier 1 VIP,2.2500,Efficacy,11.0,12.0,simvastatin,NaN,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451356520,NaN,1451356520,NaN,NaN,NaN
27.0,6.553869e+08,"CYP2C19*1, CYP2C19*17",CYP2C19,3,NaN,Tier 1 VIP,6.0000,Toxicity,15.0,16.0,clopidogrel,Acute coronary syndrome;Coronary Artery Disease;Hemorrhage;Myocardial Infarction,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/655386913,NaN,655386913,NaN,NaN,NaN
28.0,1.451356e+09,rs28379954,NFIB,3,NaN,NaN,0.0000,Metabolism/PK,1.0,1.0,clozapine,Schizophrenia,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451356180,NaN,1451356180,NaN,NaN,NaN
29.0,1.451152e+09,rs61974485,ARID4A,3,NaN,NaN,1.5000,Toxicity,1.0,1.0,ethanol,Alcoholism,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1451151506,NaN,1451151506,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15456,*3,Patients carrying the CYP3A4*3 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15457,*4,Patients carrying the CYP3A4*4 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15458,*5,Patients carrying the CYP3A4*5 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15459,*6,Patients carrying the CYP3A4*6 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15460,*7,Patients carrying the CYP3A4*7 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15461,*8,Patients carrying the CYP3A4*8 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15462,*9,Patients carrying the CYP3A4*9 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15463,*10,Patients carrying the CYP3A4*10 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15464,*11,Patients carrying the CYP3A4*11 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15465,*12,Patients carrying the CYP3A4*12 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15466,*13,Patients carrying the CYP3A4*13 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15467,*14,Patients carrying the CYP3A4*14 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15468,*15,Patients carrying the CYP3A4*15 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15469,*16,Patients carrying the CYP3A4*16 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15470,*17,Patients carrying the CYP3A4*17 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15471,*18,Patients carrying the CYP3A4*18 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15472,*19,Patients carrying the CYP3A4*19 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15473,*20,Patients carrying the CYP3A4*20 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15474,*21,Patients carrying the CYP3A4*21 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15475,*22,Patients carrying the CYP3A4*22 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15476,*23,Patients carrying the CYP3A4*23 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15477,*24,Patients carrying the CYP3A4*24 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15478,*26,Patients carrying the CYP3A4*26 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15479,*28,Patients carrying the CYP3A4*28 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15480,*29,Patients carrying the CYP3A4*29 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15481,*30,Patients carrying the CYP3A4*30 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15482,*31,Patients carrying the CYP3A4*31 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15483,*32,Patients carrying the CYP3A4*32 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15484,*33,Patients carrying the CYP3A4*33 allele may have decreased clearance of oxycodone as comapred to patients with two copies of the *1 allele. This annotation only covers the pharmacokinetic relationship between CYP3A4 and oxycodone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence oxycodone clearance.,NaN

In [88]:
merged = pd.merge(clinical_annotations, clinical_ann_alleles, on='Clinical Annotation ID')

In [131]:
pd.merge(merged, merged.groupby(by='Clinical Annotation ID').aggregate(all_genotypes=('Genotype/Allele', list)), on='Clinical Annotation ID')

,Clinical Annotation ID,Variant/Haplotypes,Gene,Level of Evidence,Level Override,Level Modifiers,Score,Phenotype Category,PMID Count,Evidence Count,Drug(s),Phenotype(s),Latest History Date (YYYY-MM-DD),URL,Specialty Population,Genotype/Allele,Annotation Text,Allele Function,all genotypes,all_genotypes
0,981755803,rs75527207,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,234.875,Efficacy,28,30,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981755803,Pediatric,AA,"Patients with the rs75527207 AA genotype (two copies of the CFTR G551D variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.",NaN,NaN,"[AA, AG, GG]"
1,981755803,rs75527207,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,234.875,Efficacy,28,30,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981755803,Pediatric,AG,"Patients with the rs75527207 AG genotype (one copy of the CFTR G551D variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.",NaN,NaN,"[AA, AG, GG]"
2,981755803,rs75527207,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,234.875,Efficacy,28,30,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981755803,Pediatric,GG,"Patients with the rs75527207 GG genotype (do not have a copy of the CFTR G551D variant) and cystic fibrosis have an unknown response to ivacaftor treatment, as response may depend on the presence of other CFTR variants. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.",NaN,NaN,"[AA, AG, GG]"
3,1449311190,rs4149056,SLCO1B1,3,NaN,Tier 1 VIP,2.000,Dosage,1,1,mercaptopurine;methotrexate,Precursor Cell Lymphoblastic Leukemia-Lymphoma,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449311190,Pediatric,CC,"Patients with the CC genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need a decreased dose of mercaptopurine, or methotrexate, as compared to children with the TT genotype. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.",NaN,NaN,"[CC, CT, TT]"
4,1449311190,rs4149056,SLCO1B1,3,NaN,Tier 1 VIP,2.000,Dosage,1,1,mercaptopurine;methotrexate,Precursor Cell Lymphoblastic Leukemia-Lymphoma,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449311190,Pediatric,CT,"Patients with the CT genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need a decreased dose of mercaptopurine, or methotrexate, as compared to children with the TT genotype. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.",NaN,NaN,"[CC, CT, TT]"
5,1449311190,rs4149056,SLCO1B1,3,NaN,Tier 1 VIP,2.000,Dosage,1,1,mercaptopurine;methotrexate,Precursor Cell Lymphoblastic Leukemia-Lymphoma,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449311190,Pediatric,TT,"Patients with the TT genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need an increased dose of mercaptopurine, or methotrexate, as compared to children with the CC or CT genotypes. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.",NaN,NaN,"[CC, CT, TT]"
6,981204774,rs1799971,OPRM1,4,NaN,NaN,-2.000,Efficacy,2,3,Drugs used in nicotine dependence;nicotine,Tobacco Use Disorder,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981204774,NaN,AA,"Patients with AA genotype may have an increased likelihood of smoking cessation when treated with nicotine replacement therapy (transdermal nicotine patch) as compared to patients with the AG and GG genotype. However, contradictory findings reporting the opposite association for this genotype with decreased likelihood of smoking cessation have been published. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation.",NaN,NaN,"[AA, AG, GG]"
7,981204774,rs1799971,OPRM1,4,NaN,NaN,-2.000,Efficacy,2,3,Drugs used in nicotine dependence;nicotine,Tobacco Use Disorder,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981204774,NaN,AG,"Patients with AG genotype may have a decreased likelihood of smoking cessation when treated with nicotine replacement therapy (transdermal nicotine patch) as compared to patients with the AA genotype. However, contradictory findings reporting the opposite association for this genotype with increased likelihood of smoking cessation have been published. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation.",NaN,NaN,"[AA, AG, GG]"
8,981204774,rs1799971,OPRM1,4,NaN,NaN,-2.000,Efficacy,2,3,Drugs used in nicotine dependence;nicotine,Tobacco Use Disorder,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981204774,NaN,GG,"Patients with GG genotype may have a decreased likelihood of smoking cessation when treated with nicotine replacement therapy (transdermal nicotine patch) as compared to patients with the AA genotype. However, contradictory findings reporting the opposite association for this genotype with increased likelihood of smoking cessation have been published. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation.",NaN,NaN,"[AA, AG, GG]"
9,1449191690,rs141033578,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,200.000,Efficacy,1,3,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449191690,NaN,CC,"Patients with the CC genotype (do not have a copy of the CFTR S977F variant) and cystic fibrosis have an unknown response to ivacaftor treatment, as response may depend on the presence of other CFTR variants. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including S977F. Other genetic and clinical factors may also influence response to ivacaftor.",NaN,NaN,"[CC, CT, TT]"
10,1449191690,rs141033578,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,200.000,Efficacy,1,3,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449191690,NaN,CT,"Patients with the CT genotype (one copy of the CFTR S977F variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including S977F. Other genetic and clinical factors may also influence response to ivacaftor.",NaN,NaN,"[CC, CT, TT]"
11,1449191690,rs141033578,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,200.000,Efficacy,1,3,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449191690,NaN,TT,"Patients with the TT genotype (two copies of the CFTR S977F variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including S977F. Other genetic and clinical factors may also influence response to ivacaftor.",NaN,NaN,"[CC, CT, TT]"
12,1449191746,rs78769542,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,200.000,Efficacy,1,3,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449191746,NaN,AA,"Patients with the AA genotype (two copies of the CFTR R1070Q variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including R1070Q. Other genetic and clinical factors may also influence response to ivacaftor.",NaN,NaN,"[AA, AG, GG]"
13,1449191746,rs78769542,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,200.000,Efficacy,1,3,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449191746,NaN,AG,"Patients with the AG genotype (one copy of the CFTR R1070Q variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including R1070Q. Other genetic and clinical factors may also influence response to ivacaftor.",NaN,NaN,"[AA, AG, GG]"
14,1449191746,rs78769542,CFTR,1A,NaN,Rare Variant; Tier 1 VIP,200.000,Efficacy,1,3,ivacaftor,Cystic Fibrosis,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449191746,NaN,GG,"Patients with the GG genotype (do not have a copy of the CFTR R1070Q variant) and cystic fibrosis have an unknown response to ivacaftor treatment, as response may depend on the presence of other CFTR variants. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including R1070Q. Other genetic and clinical factors may also influence response to ivacaftor.",NaN,NaN,"[AA, AG, GG]"
15,981419532,rs4693075,COQ2,3,NaN,NaN,3.250,Toxicity,3,3,atorvastatin;hmg coa reductase inhibitors;rosuvastatin,Muscular Diseases,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981419532,NaN,CC,Patients with the CC genotype may have decreased risk of statin-related muscle symptoms as compared to patients with genotype GG or CG. Other genetic and clinical factors may also influence a patient's risk of toxicity.,NaN,NaN,"[CC, CG, GG]"
16,981419532,rs4693075,COQ2,3,NaN,NaN,3.250,Toxicity,3,3,atorvastatin;hmg coa reductase inhibitors;rosuvastatin,Muscular Diseases,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981419532,NaN,CG,Patients with the CG genotype may have increased risk of statin-related muscle symptoms as compared to patients with genotype CC. Other genetic and clinical factors may also influence a patient's risk of toxicity.,NaN,NaN,"[CC, CG, GG]"
17,981419532,rs4693075,COQ2,3,NaN,NaN,3.250,Toxicity,3,3,atorvastatin;hmg coa reductase inhibitors;rosuvastatin,Muscular Diseases,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/981419532,NaN,GG,Patients with the GG genotype may have increased risk of statin-related muscle symptoms as compared to patients with genotype CC. Other genetic and clinical factors may also influence a patient's risk of toxicity.,NaN,NaN,"[CC, CG, GG]"
18,1449566379,rs11065987,NaN,3,NaN,NaN,2.500,Efficacy,1,1,hydrochlorothiazide,Hypertension,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449566379,NaN,AA,"Patients with the AA genotype and hypertension may have an increased response to hydrochlorothiazide treatment, as measured by decreases in systolic and diastolic blood pressure, as compared to patients with the AG or GG genotypes. Other genetic and clinical factors may also affect a patient's response to hydrochlorothiazide.",NaN,NaN,"[AA, AG, GG]"
19,1449566379,rs11065987,NaN,3,NaN,NaN,2.500,Efficacy,1,1,hydrochlorothiazide,Hypertension,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449566379,NaN,AG,"Patients with the AG genotype and hypertension may have an increased response to hydrochlorothiazide treatment, as measured by decreases in systolic and diastolic blood pressure, as compared to patients with the GG genotype, but a decreased response as compared to patients with the AA genotype. Other genetic and clinical factors may also affect a patient's response to hydrochlorothiazide.",NaN,NaN,"[AA, AG, GG]"
20,1449566379,rs11065987,NaN,3,NaN,NaN,2.500,Efficacy,1,1,hydrochlorothiazide,Hypertension,2021-03-24,https://www.pharmgkb.org/clinicalAnnotation/1449566379,NaN,GG,"Patients with the GG genotype and hypertension may have a decreased response to hydrochlorothiazide treatment, as measured by decreases in systolic and diastolic blood pressure, as compared to patients with the AA or AG genotypes. Other genetic and clinical factors may also affect a patient's response to hydrochlorothiazide.",NaN,NaN,"[AA, AG, GG]"
21,981419266,HLA-B*15:02:01,HLA-B,1A,NaN,Tier 1 VIP,315.750,Toxicity,18,23,phenytoin,"drug reaction with eosinophilia and systemic symptoms;Epidermal Necrolysis, Toxic;severe cutaneous adverse reactions;Stevens-Johnson Syndrome",2022-06-22,https://www.pharmgkb.org/clinicalAnnotation/981419266,Pediatric,*15:02:01,"Patients with one or two copies of the HLA-B*15:02:01 allele may have an increased risk of Severe Cutaneous Adverse Reactions, such as Stevens-Johnson Syndrome and Toxic Epidermal Necrolysis, when treated with phenytoin as compared to patients with no HLA-B*15:02:01 alleles or negative for the HLA-B*15:02:01 test. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence risk of phenytoin-induced adverse reactions.",Presence,NaN,[*15:02:01]
22,1451259580,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*10, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,211.375,Toxicity,6,9,amitriptyline,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451259580,NaN,*1,The CYP2D6*1 allele is assigned as a normal function allele by CPIC. Patients carrying the CYP2D6*1 allele in combination with alleles that result in a normal metabolizer phenotype who are treated with amitriptyline may have decreased likelihood of side effects as compared to patients with a combination of alleles that result in intermediate or poor metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,Normal function,NaN,"[*1, *1xN, *2, *3, *4, *5, *6, *10, *41]"
23,1451259580,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*10, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,211.375,Toxicity,6,9,amitriptyline,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451259580,NaN,*1xN,The CYP2D6*1xN alleles (*1x2 and *1x≥3) have been assigned as increased function alleles by CPIC. Patients carrying the CYP2D6*1xN allele in combination with alleles that result in a normal metabolizer phenotype who are treated with amitriptyline may have decreased likelihood of side effects as compared to patients with a combination of alleles that result in intermediate or poor metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,Increased function,NaN,"[*1, *1xN, *2, *3, *4, *5, *6, *10, *41]"
24,1451259580,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*10, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,211.375,Toxicity,6,9,amitriptyline,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451259580,NaN,*2,The CYP2D6*2 allele is assigned as a normal function allele by CPIC. Patients carrying the CYP2D6*2 allele in combination with alleles that result in a normal metabolizer phenotype who are treated with amitriptyline may have decreased likelihood of side effects as compared to patients with a combination of alleles that result in intermediate or poor metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,Normal function,NaN,"[*1, *1xN, *2, *3, *4, *5, *6, *10, *41]"
25,1451259580,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*10, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,211.375,Toxicity,6,9,amitriptyline,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451259580,NaN,*3,The CYP2D6*3 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*3 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,No function,NaN,"[*1, *1xN, *2, *3, *4, *5, *6, *10, *41]"
26,1451259580,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*10, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,211.375,Toxicity,6,9,amitriptyline,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451259580,NaN,*4,The CYP2D6*4 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*4 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,No function,NaN,"[*1, *1xN, *2, *3, *4, *5, *6, *10, *41]"
27,1451259580,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*10, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,211.375,Toxicity,6,9,amitriptyline,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451259580,NaN,*5,The CYP2D6*5 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*5 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,No function,NaN,"[*1, *1xN, *2, *3, *4, *5, *6, *10, *41]"
28,1451259580,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*10, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,211.375,Toxicity,6,9,amitriptyline,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451259580,NaN,*6,The CYP2D6*6 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*6 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,No function,NaN,"[*1, *1xN, *2, *3, *4, *5, *6, *10, *41]"
29,1451259580,"CYP2D6*1, CYP2D6*1xN, CYP2D6*2, CYP2D6*3, CYP2D6*4, CYP2D6*5, CYP2D6*6, CYP2D6*10, CYP2D6*41",CYP2D6,1A,NaN,Tier 1 VIP,211.375,Toxicity,6,9,amitriptyline,Depressive Disorder,2021-04-23,https://www.pharmgkb.org/clinicalAnnotation/1451259580,NaN,*10,The CYP2D6*10 allele is assigned as a decreased function allele with an activity value of 0.25 by CPIC. Patients carrying the CYP2D6*10 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.,Decreased function (AV 0.25),NaN,"[*1, *1xN, *2, *3, *4, *5, *6, *10, *41]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [105]:
def get_coordinates_for_clinical_annotation(rsid, all_genotypes):
    """
    Gets vcf-style coordinate string (chr_pos_ref_alt) using rsid alone, falling back on genotype information if needed.
    Returns None if coordinates cannot be determined.
    """
    chrom, pos, ref, alts = get_coordinates_for_rs(rsid)
    if not chrom or not pos or not ref or not alts:
        return None
    if len(alts) == 1:
        return f'{chrom}_{pos}_{ref}_{alts[0]}'
    # If multiple alts, check what is referred to in the clinical alleles table
    alleles = set()
    for genotype in all_genotypes:
        # X chrom variants
        if len(genotype) == 1:
            alleles.add(genotype)
            continue
        # SNPs
        if len(genotype) == 2:
            alleles.add(genotype[0])
            alleles.add(genotype[1])
            continue
        # short indels
        m = re.match('([ACGT]+|del)/([ACGT]+|del)', genotype, re.IGNORECASE)
        if not m:
            continue
        alleles.add(convert_allele(m.group(1)))
        alleles.add(convert_allele(m.group(2)))
    if len(alleles) > 2:
        logger.warning(f'Too many alleles for rs{rsid}, skipping')
        return None
    for a in alleles:
        if a in alts:
            return f'{chrom}_{pos}_{ref}_{a}'
    return None


def convert_allele(allele):
    # TODO "del" alleles are an issue for chr_pos_ref_alt - need context bases
    if allele.lower() == 'del':
        return '-'
    return allele


def get_coordinates_for_rs(rsid):
    """Queries Ensembl for vcf-style coordinates for rsid. Returns None if not found."""
    # TODO do this in bulk (batches of 200) or replace with reference FASTA check
    if not rsid.startswith('rs'):
        rsid = f'rs{rsid}'
    ensembl_url = f'https://rest.ensembl.org/variation/human/{rsid}?content-type=application/json'
    resp = requests.get(ensembl_url)
    data = resp.json()
    if 'mappings' in data:
        mapping = None
        for mapping in data['mappings']:
            if mapping['assembly_name'] == 'GRCh38':
                break
        if mapping:
            chrom = mapping['seq_region_name']
            pos = mapping['start']
            alleles = mapping['allele_string'].split('/')
            ref = alleles[0]
            alts = alleles[1:]
            return chrom, pos, ref, alts
    return None, None, None, None

In [107]:
rs_only_table = ca_with_rs.assign(
    vcf_coords=lambda df: get_coordinates_for_clinical_annotation(
        row['Variant/Haplotypes'].iloc[0],
        clinical_ann_alleles[clinical_ann_alleles['Clinical Annotation ID'] == row['Clinical Annotation ID'].iloc[0]]['Genotype/Allele']
    )
)

In [109]:
rs_only_table['vcf_coords'] = [get_coordinates_for_clinical_annotation(
    row['Variant/Haplotypes'].iloc[0],
    clinical_ann_alleles[clinical_ann_alleles['Clinical Annotation ID'] == row['Clinical Annotation ID'].iloc[0]][
        'Genotype/Allele']
) for row in ca_with_rs]

TypeError: string indices must be integers

In [110]:
[row for row in ca_with_rs]

['Clinical Annotation ID',
 'Variant/Haplotypes',
 'Gene',
 'Level of Evidence',
 'Level Override',
 'Level Modifiers',
 'Score',
 'Phenotype Category',
 'PMID Count',
 'Evidence Count',
 'Drug(s)',
 'Phenotype(s)',
 'Latest History Date (YYYY-MM-DD)',
 'URL',
 'Specialty Population']

In [137]:
caids = {1183680546, 1451114960, 1448603303, 981419260, 1444668808, 1449309937, 1043880328, 1447680028, 1450375701}

In [141]:
clinical_annotations[clinical_annotations['Clinical Annotation ID'].isin(caids)].to_csv('/home/april/projects/opentargets-pharmgkb/tests/resources/clinical_annotation_sample.tsv',
                                                                                       sep='\t', index=False)

In [142]:
clinical_ann_alleles[clinical_ann_alleles['Clinical Annotation ID'].isin(caids)].to_csv('/home/april/projects/opentargets-pharmgkb/tests/resources/clinical_ann_alleles_sample.tsv',
                                                                                       sep='\t', index=False)